/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedUserStatus } from './apiHydratedUserStatus';
import type { MultiFactorSettings } from './multiFactorSettings';
import type { ServiceIntegrations } from './serviceIntegrations';
import type { StateToken } from './stateToken';
import type { UserPreferences } from './userPreferences';

export interface ApiHydratedUser {
  /** First name */
  firstName: string;
  /** Last name */
  lastName: string;
  /** Email address */
  email: string;
  /** Phone number */
  phone?: string;
  /** Whether email is confirmed */
  emailConfirmed: boolean;
  /** Hashed password */
  passwordHash: string;
  /** Account status */
  status: ApiHydratedUserStatus;
  /** Role IDs */
  roles: string[];
  /** Business ID */
  business: string;
  /** State token for email verification */
  stateToken?: StateToken;
  /** Multi-factor authentication settings */
  multiFactors?: MultiFactorSettings[];
  /** Service integrations */
  integration?: ServiceIntegrations;
  /** User preferences */
  preferences?: UserPreferences;
  /** Whether multi-factor auth is enabled */
  multiFactorEnabled?: boolean;
  /** Full name (virtual) */
  fullName?: string;
  /** Whether identity is confirmed */
  identityConfirmed?: boolean;
  /** Document id */
  id: string;
  /** Document created at */
  createdAt: string;
  /** Document updated at */
  updatedAt: string;
}
