/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Transaction currency
 */
export type ApiHydratedCardBinAccountLogCurrency = typeof ApiHydratedCardBinAccountLogCurrency[keyof typeof ApiHydratedCardBinAccountLogCurrency];


export const ApiHydratedCardBinAccountLogCurrency = {
  USD: 'USD',
  NGN: 'NGN',
} as const;
