/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Card program status
 */
export type ApiHydratedCardProgramStatus = typeof ApiHydratedCardProgramStatus[keyof typeof ApiHydratedCardProgramStatus];


export const ApiHydratedCardProgramStatus = {
  new: 'new',
  'approval-requested': 'approval-requested',
  'under-review': 'under-review',
  'changes-requested': 'changes-requested',
  approved: 'approved',
  manufacturing: 'manufacturing',
  personalising: 'personalising',
  testing: 'testing',
  live: 'live',
  suspended: 'suspended',
} as const;
