/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Dispute reason
 */
export type ApiHydratedDisputeReason = typeof ApiHydratedDisputeReason[keyof typeof ApiHydratedDisputeReason];


export const ApiHydratedDisputeReason = {
  fraudulent: 'fraudulent',
  duplicate: 'duplicate',
  'value-not-received': 'value-not-received',
  general: 'general',
} as const;
