/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedCardProgramCurrency } from './apiHydratedCardProgramCurrency';
import type { ApiHydratedCardProgramNetwork } from './apiHydratedCardProgramNetwork';
import type { ApiHydratedCardProgramStatus } from './apiHydratedCardProgramStatus';
import type { ApiHydratedCardProgramType } from './apiHydratedCardProgramType';
import type { CardProgramAuthorization } from './cardProgramAuthorization';
import type { CardProgramConfig } from './cardProgramConfig';
import type { CardProgramDistribution } from './cardProgramDistribution';
import type { CardProgramPersonalization } from './cardProgramPersonalization';

export interface ApiHydratedCardProgram {
  /** Card program name */
  name: string;
  /** Card program description */
  description?: string;
  /** Card network */
  network: ApiHydratedCardProgramNetwork;
  /** Card type */
  type: ApiHydratedCardProgramType;
  /** Total card quantity */
  quantity?: number;
  /** Card currency */
  currency: ApiHydratedCardProgramCurrency;
  /** Card personalization settings */
  personalization?: CardProgramPersonalization;
  /** Card distribution settings */
  distribution?: CardProgramDistribution;
  /** Card authorization settings */
  authorization: CardProgramAuthorization;
  /** Card program configuration */
  config?: CardProgramConfig;
  /** Card BIN ID */
  bin?: string;
  /** Business ID */
  business: string;
  /** Card program status */
  status: ApiHydratedCardProgramStatus;
  /** Document id */
  id: string;
  /** Document created at */
  createdAt: string;
  /** Document updated at */
  updatedAt: string;
}
