/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Customer type
 */
export type ApiHydratedCustomerType = typeof ApiHydratedCustomerType[keyof typeof ApiHydratedCustomerType];


export const ApiHydratedCustomerType = {
  individual: 'individual',
  business: 'business',
} as const;
