/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Request status
 */
export type ApiHydratedApiRequestStatus = typeof ApiHydratedApiRequestStatus[keyof typeof ApiHydratedApiRequestStatus];


export const ApiHydratedApiRequestStatus = {
  completed: 'completed',
  pending: 'pending',
  cancelled: 'cancelled',
} as const;
