/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface ApiHydratedBusinessLeadership {
  /** First name */
  firstName: string;
  /** Middle name */
  middleName?: string;
  /** Last name */
  lastName: string;
  /** Role or title within the business */
  role: string;
  /** Nationality country code */
  nationalityCode: string;
  /** Phone number */
  phone: string;
  /** Email address */
  email: string;
  /** Date of birth */
  dateOfBirth: string;
  /** Bank Verification Number */
  bvn: string;
  /** PayKKa file ID for identity document */
  paykkaDocFileId?: number;
  /** Document id */
  id: string;
  /** Document created at */
  createdAt: string;
  /** Document updated at */
  updatedAt: string;
}
