/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * API version
 */
export type ApiHydratedSecretKeyApiVersion = typeof ApiHydratedSecretKeyApiVersion[keyof typeof ApiHydratedSecretKeyApiVersion];


export const ApiHydratedSecretKeyApiVersion = {
  '2024-05-01': '2024-05-01',
  '2023-02-01': '2023-02-01',
} as const;
