/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Payment status
 */
export type ApiHydratedPaymentStatus = typeof ApiHydratedPaymentStatus[keyof typeof ApiHydratedPaymentStatus];


export const ApiHydratedPaymentStatus = {
  queued: 'queued',
  new: 'new',
  pending: 'pending',
  failed: 'failed',
  success: 'success',
  expired: 'expired',
} as const;
