/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedCardBinBinLength } from './apiHydratedCardBinBinLength';
import type { ApiHydratedCardBinNetwork } from './apiHydratedCardBinNetwork';
import type { ApiHydratedCardBinProvider } from './apiHydratedCardBinProvider';
import type { ApiHydratedCardBinStatus } from './apiHydratedCardBinStatus';
import type { ApiHydratedCardBinType } from './apiHydratedCardBinType';
import type { CardBinConfig } from './cardBinConfig';

export interface ApiHydratedCardBin {
  /** BIN name */
  name: string;
  /** BIN type */
  type: ApiHydratedCardBinType;
  /** BIN description */
  description?: string;
  /** BIN hash (unique) */
  binHash?: string;
  /** Card network */
  network: ApiHydratedCardBinNetwork;
  /** Bank provider */
  provider: ApiHydratedCardBinProvider;
  /** BIN account number */
  binAccountNumber?: string;
  /** BIN length */
  binLength: ApiHydratedCardBinBinLength;
  /** BIN range */
  binRange?: string;
  /** BIN configuration */
  config?: CardBinConfig;
  /** BIN status */
  status: ApiHydratedCardBinStatus;
  /** Document id */
  id: string;
  /** Document created at */
  createdAt: string;
  /** Document updated at */
  updatedAt: string;
}
