/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Card currency
 */
export type ApiHydratedCardProgramCurrency = typeof ApiHydratedCardProgramCurrency[keyof typeof ApiHydratedCardProgramCurrency];


export const ApiHydratedCardProgramCurrency = {
  USD: 'USD',
  NGN: 'NGN',
} as const;
