/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedWebhookApiVersion } from './apiHydratedWebhookApiVersion';
import type { ApiHydratedWebhookEventsItem } from './apiHydratedWebhookEventsItem';
import type { ApiHydratedWebhookMetadata } from './apiHydratedWebhookMetadata';

export interface ApiHydratedWebhook {
  /** Webhook name */
  name: string;
  /** Webhook description */
  description?: string;
  /** Is webhook disabled */
  disabled: boolean;
  /** Subscribed event types */
  events: ApiHydratedWebhookEventsItem[];
  /** API version */
  apiVersion: ApiHydratedWebhookApiVersion;
  /** Webhook endpoint URL */
  url: string;
  /** Webhook signing key (revealed on request) */
  signingKey?: string;
  /** Additional metadata */
  metadata?: ApiHydratedWebhookMetadata;
  /** Document id */
  id: string;
  /** Document created at */
  createdAt: string;
  /** Document updated at */
  updatedAt: string;
}
