/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Dispute status
 */
export type ApiHydratedDisputeStatus = typeof ApiHydratedDisputeStatus[keyof typeof ApiHydratedDisputeStatus];


export const ApiHydratedDisputeStatus = {
  new: 'new',
  'under-review': 'under-review',
  'awaiting-response': 'awaiting-response',
  closed: 'closed',
  resolved: 'resolved',
} as const;
