/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Decline reason
 */
export type ApiHydratedCardAuthorizationDeclineReason = typeof ApiHydratedCardAuthorizationDeclineReason[keyof typeof ApiHydratedCardAuthorizationDeclineReason];


export const ApiHydratedCardAuthorizationDeclineReason = {
  'insufficient-funds': 'insufficient-funds',
  'account-inactive': 'account-inactive',
  'account-not-found': 'account-not-found',
  'spending-control': 'spending-control',
  'timeout-default': 'timeout-default',
  'invalid-transaction': 'invalid-transaction',
  'system-failure': 'system-failure',
  'invalid-response': 'invalid-response',
  'authorization-declined': 'authorization-declined',
} as const;
