/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Card status
 */
export type ApiHydratedCardStatus = typeof ApiHydratedCardStatus[keyof typeof ApiHydratedCardStatus];


export const ApiHydratedCardStatus = {
  REQUIRES_SETUP: 'REQUIRES_SETUP',
  REQUIRES_ACTIVATION: 'REQUIRES_ACTIVATION',
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
  RETIRED: 'RETIRED',
} as const;
