/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * KYC submission status
 */
export type ApiHydratedBusinessKYCStatus = typeof ApiHydratedBusinessKYCStatus[keyof typeof ApiHydratedBusinessKYCStatus];


export const ApiHydratedBusinessKYCStatus = {
  incomplete: 'incomplete',
  submitted: 'submitted',
  approved: 'approved',
  rejected: 'rejected',
  'needs-update': 'needs-update',
} as const;
