/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * BIN length
 */
export type ApiHydratedCardBinBinLength = typeof ApiHydratedCardBinBinLength[keyof typeof ApiHydratedCardBinBinLength];


export const ApiHydratedCardBinBinLength = {
  '100k': '100k',
  '1m': '1m',
  '10m': '10m',
  '100m': '100m',
} as const;
