/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Object model reference
 */
export type ApiHydratedAuditObjectRef = typeof ApiHydratedAuditObjectRef[keyof typeof ApiHydratedAuditObjectRef];


export const ApiHydratedAuditObjectRef = {
  User: 'User',
  Approval: 'Approval',
  AccessKey: 'AccessKey',
  CardProgram: 'CardProgram',
  Webhook: 'Webhook',
  ShippingAddress: 'ShippingAddress',
} as const;
