/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { APIRequestAttemptResponseBody } from './aPIRequestAttemptResponseBody';

export interface APIRequestAttempt {
  /** Response body of this attempt */
  responseBody?: APIRequestAttemptResponseBody;
  /** HTTP status code */
  statusCode: number;
  /** Request latency in milliseconds */
  latency: number;
  /** Attempt timestamp */
  createdAt: string;
}
