/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { BillingConfigurationAddress } from './billingConfigurationAddress';

export interface BillingConfiguration {
  /** Billing account ID */
  account: string;
  /** Business name for billing */
  businessName?: string;
  /** Billing contact first name */
  contactFirstName?: string;
  /** Billing contact last name */
  contactLastName?: string;
  /** Card billing rate */
  cardBillingRate?: number;
  /** Card list rate */
  cardListRate?: number;
  /** Card billing unit */
  cardBillingUnit?: string;
  /** Cross-border fee rate */
  crossBorderFeeRate?: number;
  /** Billing address */
  address?: BillingConfigurationAddress;
}
