/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface BusinessLeadership {
  /** First name */
  firstName: string;
  /** Middle name */
  middleName?: string;
  /** Last name */
  lastName: string;
  /** Role in the business */
  role: string;
  /** Nationality country code */
  nationalityCode: string;
  /** Phone number */
  phone: string;
  /** Email address */
  email: string;
  /** Date of birth */
  dateOfBirth: string;
  /** BVN */
  bvn: string;
}
