/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Profile code
 */
export type CardProgramConfigProfile = typeof CardProgramConfigProfile[keyof typeof CardProgramConfigProfile];


export const CardProgramConfigProfile = {
  'verve-live': 'verve-live',
  'verve-sandbox': 'verve-sandbox',
  'pavilion-mastercard-live': 'pavilion-mastercard-live',
  'pavilion-mastercard-sandbox': 'pavilion-mastercard-sandbox',
  'maplerad-mastercard-live': 'maplerad-mastercard-live',
  'maplerad-mastercard-sandbox': 'maplerad-mastercard-sandbox',
} as const;
