/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CardBinConfigPartner } from './cardBinConfigPartner';
import type { CardBinConfigProfile } from './cardBinConfigProfile';

export interface CardBinConfig {
  /** Card partner */
  partner: CardBinConfigPartner;
  /** BIN profile code */
  profile: CardBinConfigProfile;
  /** Partner profile identifier */
  partnerProfile?: string;
  /** Partner access key */
  partnerAccessKey?: string;
  /** Partner access ID */
  partnerAccessId?: string;
}
