/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface CardProgramPersonalization {
  /** Front artwork file path */
  frontArtworkFile?: string;
  /** Whether to print cardholder name on card */
  printCardholderName: boolean;
  /** Default cardholder name printed on card */
  defaultCardholderName: string;
}
