/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Card partner
 */
export type CardDetailsPartner = typeof CardDetailsPartner[keyof typeof CardDetailsPartner];


export const CardDetailsPartner = {
  FLUTTERWAVE: 'FLUTTERWAVE',
  MAPLERAD: 'MAPLERAD',
  INTERSWITCH: 'INTERSWITCH',
} as const;
