/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface CardAuthVolumeStats {
  /** Total amount */
  total: number;
  /** Total fees */
  fees: number;
  /** Transaction count */
  count: number;
  /**
     * Percentage change vs previous period
     * @nullable
     */
  change: number | null;
}
