/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CardProgramConfigPartner } from './cardProgramConfigPartner';
import type { CardProgramConfigProfile } from './cardProgramConfigProfile';

export interface CardProgramConfig {
  /** Card program partner */
  partner?: CardProgramConfigPartner;
  /** Batch number */
  batchNumber?: string;
  /** Profile code */
  profile?: CardProgramConfigProfile;
  /** Partner profile identifier */
  partnerProfile?: string;
  /** Partner access key */
  partnerAccessKey?: string;
  /** Partner access ID */
  partnerAccessId?: string;
}
