/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type CreatePayoutPaymentDtoCurrency = typeof CreatePayoutPaymentDtoCurrency[keyof typeof CreatePayoutPaymentDtoCurrency];


export const CreatePayoutPaymentDtoCurrency = {
  USD: 'USD',
  NGN: 'NGN',
} as const;
