/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CreatePaymentRequestDtoCurrency } from './createPaymentRequestDtoCurrency';
import type { CreatePaymentRequestDtoMetadata } from './createPaymentRequestDtoMetadata';
import type { CreatePaymentRequestDtoMethod } from './createPaymentRequestDtoMethod';
import type { CreatePaymentRequestDtoOptions } from './createPaymentRequestDtoOptions';

export interface CreatePaymentRequestDto {
  method: CreatePaymentRequestDtoMethod;
  currency: CreatePaymentRequestDtoCurrency;
  amount: number;
  /** Method-specific options */
  options?: CreatePaymentRequestDtoOptions;
  reference?: string;
  narration?: string;
  /** Customer ID */
  customer?: string;
  metadata?: CreatePaymentRequestDtoMetadata;
}
