/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type CreatePaymentRequestDtoMethod = typeof CreatePaymentRequestDtoMethod[keyof typeof CreatePaymentRequestDtoMethod];


export const CreatePaymentRequestDtoMethod = {
  'bank-transfer': 'bank-transfer',
  'payment-authorization': 'payment-authorization',
} as const;
