/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CreateDisputeDtoReason } from './createDisputeDtoReason';

export interface CreateDisputeDto {
  reason: CreateDisputeDtoReason;
  /** Source ID (Card Authorization, Card Transaction, or Payment) */
  source: string;
  text?: string;
  documents?: string[];
}
