/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type CreatePayoutPaymentDtoMethod = typeof CreatePayoutPaymentDtoMethod[keyof typeof CreatePayoutPaymentDtoMethod];


export const CreatePayoutPaymentDtoMethod = {
  'bank-transfer': 'bank-transfer',
  transfer: 'transfer',
  'local-transfer': 'local-transfer',
  refund: 'refund',
} as const;
