/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CreateCardBinDtoBinLength } from './createCardBinDtoBinLength';
import type { CreateCardBinDtoNetwork } from './createCardBinDtoNetwork';
import type { CreateCardBinDtoProvider } from './createCardBinDtoProvider';

export interface CreateCardBinDto {
  name: string;
  description?: string;
  network: CreateCardBinDtoNetwork;
  provider: CreateCardBinDtoProvider;
  binLength: CreateCardBinDtoBinLength;
}
