/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Verification Type
 */
export type CustomerVerificationDtoType = typeof CustomerVerificationDtoType[keyof typeof CustomerVerificationDtoType];


export const CustomerVerificationDtoType = {
  'tier-0': 'tier-0',
  'tier-1': 'tier-1',
  'tier-2': 'tier-2',
  'tier-3': 'tier-3',
} as const;
