/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Identification Type
 */
export type CustomerIndividualIdentityDtoType = typeof CustomerIndividualIdentityDtoType[keyof typeof CustomerIndividualIdentityDtoType];


export const CustomerIndividualIdentityDtoType = {
  bvn: 'bvn',
  'drivers-license': 'drivers-license',
  nin: 'nin',
  'voters-card': 'voters-card',
  passport: 'passport',
} as const;
