/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CustomerVerificationStatus } from './customerVerificationStatus';
import type { CustomerVerificationType } from './customerVerificationType';

export interface CustomerVerification {
  /** Verification tier */
  type?: CustomerVerificationType;
  /** Verification status */
  status?: CustomerVerificationStatus;
}
