/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Customer Type
 */
export type CustomerDtoType = typeof CustomerDtoType[keyof typeof CustomerDtoType];


export const CustomerDtoType = {
  individual: 'individual',
  business: 'business',
} as const;
