/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Gender
 */
export type CustomerBusinessDirectorDtoGender = typeof CustomerBusinessDirectorDtoGender[keyof typeof CustomerBusinessDirectorDtoGender];


export const CustomerBusinessDirectorDtoGender = {
  M: 'M',
  F: 'F',
} as const;
