/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CustomerIndividualInformationDtoGender } from './customerIndividualInformationDtoGender';

export interface CustomerIndividualInformationDto {
  /** Title */
  title?: string;
  /** Gender */
  gender?: CustomerIndividualInformationDtoGender;
  /** Nationality in ISO Country Code */
  nationalityCode: string;
  /** First Name */
  firstName: string;
  /** Middle Name */
  middleName?: string;
  /** Last Name */
  lastName: string;
  /** Phone Number with Calling Code */
  phoneNumber: string;
  /** Date of Birth */
  dateOfBirth?: string;
  /** Email Address */
  email?: string;
}
