/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CustomerIndividualIdentityType } from './customerIndividualIdentityType';

export interface CustomerIndividualIdentity {
  /** Identity type */
  type?: CustomerIndividualIdentityType;
  /** Identity ID number */
  id?: string;
  /** Identity document URL */
  url?: string;
  /** Issuing country code */
  issuingCountry?: string;
}
