/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { DashboardControllerGetMetricsPeriod } from './dashboardControllerGetMetricsPeriod';

export type DashboardControllerGetMetricsParams = {
/**
 * Period for treasury stats
 */
period?: DashboardControllerGetMetricsPeriod;
};
