/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { TreasuryCountChangeStatsDto } from './treasuryCountChangeStatsDto';
import type { TreasuryDailyVolumeStatDto } from './treasuryDailyVolumeStatDto';
import type { TreasuryFlowSplitStatDto } from './treasuryFlowSplitStatDto';
import type { TreasuryRateChangeStatsDto } from './treasuryRateChangeStatsDto';
import type { TreasuryStatusStatDto } from './treasuryStatusStatDto';
import type { TreasuryVolumeStatsDto } from './treasuryVolumeStatsDto';

export interface DashboardMetricsResponseDto {
  /** Currency code */
  currency: string;
  /** Pay-in collections volume */
  collections: TreasuryVolumeStatsDto;
  /** Daily pay-in collections volume */
  dailyCollections: TreasuryDailyVolumeStatDto[];
  /** Successful pay-in count */
  payIns: TreasuryCountChangeStatsDto;
  /** Failed or abandoned pay-in count */
  payInFailures: TreasuryCountChangeStatsDto;
  /** Pay-in success rate */
  successRate: TreasuryRateChangeStatsDto;
  /** Pay-in vs pay-out flow split */
  flowSplit: TreasuryFlowSplitStatDto[];
  /** Payments grouped by status */
  byStatus: TreasuryStatusStatDto[];
  /** Available collected balance (kobo) */
  availableBalance: number;
  /** Balance reserved for pending payouts (kobo) */
  pendingPayout: number;
}
