/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { AWSObjectURL } from './aWSObjectURL';
import type { DisputeTimelineAction } from './disputeTimelineAction';
import type { DisputeTimelineActorType } from './disputeTimelineActorType';

export interface DisputeTimeline {
  /** Timeline action */
  action: DisputeTimelineAction;
  /** Actor type */
  actorType: DisputeTimelineActorType;
  /** User actor ID */
  user?: string;
  /** Customer actor ID */
  customer?: string;
  /** Timeline note text */
  text?: string;
  /** Supporting documents */
  documents?: AWSObjectURL[];
}
