/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { FxBuyQuoteDtoFromCurrency } from './fxBuyQuoteDtoFromCurrency';
import type { FxBuyQuoteDtoToCurrency } from './fxBuyQuoteDtoToCurrency';

export interface FxBuyQuoteDto {
  fromCurrency: FxBuyQuoteDtoFromCurrency;
  toCurrency: FxBuyQuoteDtoToCurrency;
  toAmount: number;
}
