/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { FxQuoteDtoFrom } from './fxQuoteDtoFrom';
import type { FxQuoteDtoTo } from './fxQuoteDtoTo';

export interface FxQuoteDto {
  type?: string;
  from: FxQuoteDtoFrom;
  to: FxQuoteDtoTo;
  amount: number;
}
