/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Source currency
 */
export type FxRateFrom = typeof FxRateFrom[keyof typeof FxRateFrom];


export const FxRateFrom = {
  USD: 'USD',
  NGN: 'NGN',
} as const;
