/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { FxQuote } from './fxQuote';

export interface FxRefundPaymentMethodData {
  /** Refund currency */
  currency?: string;
  /** Refund amount */
  amount?: number;
  /** Quote hash */
  hash?: string;
  /** Exchange rate */
  rate?: number;
  /** Related object ID */
  for?: string;
  /** FX quote details */
  fxQuote?: FxQuote;
  /** Refund type */
  type?: string;
}
