/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type FxSellQuoteDtoFromCurrency = typeof FxSellQuoteDtoFromCurrency[keyof typeof FxSellQuoteDtoFromCurrency];


export const FxSellQuoteDtoFromCurrency = {
  USD: 'USD',
  NGN: 'NGN',
} as const;
