/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type FxSellQuoteDtoToCurrency = typeof FxSellQuoteDtoToCurrency[keyof typeof FxSellQuoteDtoToCurrency];


export const FxSellQuoteDtoToCurrency = {
  USD: 'USD',
  NGN: 'NGN',
} as const;
