/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { HealthControllerCheck503Details } from './healthControllerCheck503Details';
import type { HealthControllerCheck503Error } from './healthControllerCheck503Error';
import type { HealthControllerCheck503Info } from './healthControllerCheck503Info';

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};
