/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { KYCBusinessInformationRegistrationType } from './kYCBusinessInformationRegistrationType';

export interface KYCBusinessInformation {
  /** Business name */
  businessName: string;
  /** Business registration type */
  registrationType: KYCBusinessInformationRegistrationType;
  /** Business registration number */
  registrationNumber: string;
  /** Business description */
  businessDescription: string;
  /** Tax identification number */
  tin?: string;
}
