/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Business registration type
 */
export type KYCBusinessInformationRegistrationType = typeof KYCBusinessInformationRegistrationType[keyof typeof KYCBusinessInformationRegistrationType];


export const KYCBusinessInformationRegistrationType = {
  'private-limited-company': 'private-limited-company',
  'company-limited-by-guarantee': 'company-limited-by-guarantee',
  'public-limited-company': 'public-limited-company',
  'business-name': 'business-name',
  'unlimited-company': 'unlimited-company',
  'incorporated-trustees': 'incorporated-trustees',
} as const;
