/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface MerchantPattern {
  /** Affix string for pattern matching */
  affix: string;
  /** Keywords for pattern matching */
  keywords: string[];
}
