/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { PatchWebhookDtoEventsItem } from './patchWebhookDtoEventsItem';
import type { PatchWebhookDtoMetadata } from './patchWebhookDtoMetadata';

export interface PatchWebhookDto {
  name?: string;
  events?: PatchWebhookDtoEventsItem[];
  apiVersion?: string;
  description?: string;
  url?: string;
  metadata?: PatchWebhookDtoMetadata;
}
