/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CardShippingDto } from './cardShippingDto';
import type { PatchCardDtoMetadata } from './patchCardDtoMetadata';
import type { PatchSpendingControlDto } from './patchSpendingControlDto';

export interface PatchCardDto {
  controls?: PatchSpendingControlDto;
  shipping?: CardShippingDto;
  metadata?: PatchCardDtoMetadata;
}
