/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type PatchCardProgramDraftDtoNetwork = typeof PatchCardProgramDraftDtoNetwork[keyof typeof PatchCardProgramDraftDtoNetwork];


export const PatchCardProgramDraftDtoNetwork = {
  mastercard: 'mastercard',
  visa: 'visa',
  verve: 'verve',
} as const;
