/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

/**
 * Customer Type
 */
export type PatchCustomerDtoType = typeof PatchCustomerDtoType[keyof typeof PatchCustomerDtoType];


export const PatchCustomerDtoType = {
  individual: 'individual',
  business: 'business',
} as const;
