/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { UserPreferencesDto } from './userPreferencesDto';

export interface PatchProfileDto {
  firstName?: string;
  lastName?: string;
  preferences: UserPreferencesDto;
}
