/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { PatchCardBinDtoBinLength } from './patchCardBinDtoBinLength';
import type { PatchCardBinDtoNetwork } from './patchCardBinDtoNetwork';
import type { PatchCardBinDtoProvider } from './patchCardBinDtoProvider';

export interface PatchCardBinDto {
  name?: string;
  description?: string;
  network?: PatchCardBinDtoNetwork;
  provider?: PatchCardBinDtoProvider;
  binLength?: PatchCardBinDtoBinLength;
}
