/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ObjectId } from './objectId';
import type { PaymentConfigurationFeesDto } from './paymentConfigurationFeesDto';

export interface PaymentConfigurationDto {
  payInAccount?: ObjectId;
  payOutAccount?: ObjectId;
  fees?: PaymentConfigurationFeesDto;
}
