/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentFeeSetting } from './paymentFeeSetting';

export interface PaymentConfiguration {
  /** Pay-in account ID */
  payInAccount: string;
  /** Pay-out account ID */
  payOutAccount: string;
  /** Fee settings */
  fees?: PaymentFeeSetting;
}
