/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentTimelineDataCode } from './paymentTimelineDataCode';

export interface PaymentTimelineData {
  /** Timeline data code */
  code?: PaymentTimelineDataCode;
  /** Error message */
  error?: string;
  /** Balance log ID */
  balanceLog?: string;
}
