/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { Bank } from './bank';

export interface ResolvedAccount {
  /** Account holder name */
  name: string;
  /** Bank details */
  bank?: Bank;
  /** BVN */
  bvn?: string;
  /** KYC level */
  kyc?: string;
  /** NIP session ID */
  nipSessionId?: string;
}
