/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedPayment } from './apiHydratedPayment';
import type { ResponseWrapperApiHydratedPaymentCode } from './responseWrapperApiHydratedPaymentCode';

export interface ResponseWrapperApiHydratedPayment {
  code: ResponseWrapperApiHydratedPaymentCode;
  message?: string;
  /** Response data */
  data: ApiHydratedPayment;
}
