/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedSecretKey } from './apiHydratedSecretKey';
import type { APIPaginationData } from './aPIPaginationData';
import type { ResponseWrapperApiHydratedSecretKeyListCode } from './responseWrapperApiHydratedSecretKeyListCode';

export interface ResponseWrapperApiHydratedSecretKeyList {
  code: ResponseWrapperApiHydratedSecretKeyListCode;
  message: string;
  /** Response data list */
  data?: ApiHydratedSecretKey[];
  /** Pagination metadata */
  metadata?: APIPaginationData;
}
