/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedAccount } from './apiHydratedAccount';
import type { APIPaginationData } from './aPIPaginationData';
import type { ResponseWrapperApiHydratedAccountListCode } from './responseWrapperApiHydratedAccountListCode';

export interface ResponseWrapperApiHydratedAccountList {
  code: ResponseWrapperApiHydratedAccountListCode;
  message: string;
  /** Response data list */
  data?: ApiHydratedAccount[];
  /** Pagination metadata */
  metadata?: APIPaginationData;
}
