/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedUser } from './apiHydratedUser';
import type { APIPaginationData } from './aPIPaginationData';
import type { ResponseWrapperApiHydratedUserListCode } from './responseWrapperApiHydratedUserListCode';

export interface ResponseWrapperApiHydratedUserList {
  code: ResponseWrapperApiHydratedUserListCode;
  message: string;
  /** Response data list */
  data?: ApiHydratedUser[];
  /** Pagination metadata */
  metadata?: APIPaginationData;
}
