/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { CardMetricsResponseDto } from './cardMetricsResponseDto';
import type { ResponseWrapperCardMetricsResponseDtoCode } from './responseWrapperCardMetricsResponseDtoCode';

export interface ResponseWrapperCardMetricsResponseDto {
  code: ResponseWrapperCardMetricsResponseDtoCode;
  message?: string;
  /** Response data */
  data: CardMetricsResponseDto;
}
