/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedCardProgram } from './apiHydratedCardProgram';
import type { APIPaginationData } from './aPIPaginationData';
import type { ResponseWrapperApiHydratedCardProgramListCode } from './responseWrapperApiHydratedCardProgramListCode';

export interface ResponseWrapperApiHydratedCardProgramList {
  code: ResponseWrapperApiHydratedCardProgramListCode;
  message: string;
  /** Response data list */
  data?: ApiHydratedCardProgram[];
  /** Pagination metadata */
  metadata?: APIPaginationData;
}
