/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedApiRequest } from './apiHydratedApiRequest';
import type { APIPaginationData } from './aPIPaginationData';
import type { ResponseWrapperApiHydratedApiRequestListCode } from './responseWrapperApiHydratedApiRequestListCode';

export interface ResponseWrapperApiHydratedApiRequestList {
  code: ResponseWrapperApiHydratedApiRequestListCode;
  message: string;
  /** Response data list */
  data?: ApiHydratedApiRequest[];
  /** Pagination metadata */
  metadata?: APIPaginationData;
}
