/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { Merchant } from './merchant';
import type { ResponseWrapperMerchantCode } from './responseWrapperMerchantCode';

export interface ResponseWrapperMerchant {
  code: ResponseWrapperMerchantCode;
  message?: string;
  /** Response data */
  data: Merchant;
}
