/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedBusiness } from './apiHydratedBusiness';
import type { ResponseWrapperApiHydratedBusinessCode } from './responseWrapperApiHydratedBusinessCode';

export interface ResponseWrapperApiHydratedBusiness {
  code: ResponseWrapperApiHydratedBusinessCode;
  message?: string;
  /** Response data */
  data: ApiHydratedBusiness;
}
