/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedDispute } from './apiHydratedDispute';
import type { ResponseWrapperApiHydratedDisputeCode } from './responseWrapperApiHydratedDisputeCode';

export interface ResponseWrapperApiHydratedDispute {
  code: ResponseWrapperApiHydratedDisputeCode;
  message?: string;
  /** Response data */
  data: ApiHydratedDispute;
}
