/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedUser } from './apiHydratedUser';
import type { ResponseWrapperApiHydratedUserCode } from './responseWrapperApiHydratedUserCode';

export interface ResponseWrapperApiHydratedUser {
  code: ResponseWrapperApiHydratedUserCode;
  message?: string;
  /** Response data */
  data: ApiHydratedUser;
}
