/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type ResponseWrapperApiHydratedBillingCode = typeof ResponseWrapperApiHydratedBillingCode[keyof typeof ResponseWrapperApiHydratedBillingCode];


export const ResponseWrapperApiHydratedBillingCode = {
  success: 'success',
  unauthorized: 'unauthorized',
  forbidden: 'forbidden',
  'bad-request': 'bad-request',
  'not-found': 'not-found',
  conflict: 'conflict',
  'reference-conflict': 'reference-conflict',
  'worker-error': 'worker-error',
  '__configuration-error': '  configuration-error',
  'application-timeout': 'application-timeout',
  'application-error': 'application-error',
  'request-timeout': 'request-timeout',
  'service-unavailable': 'service-unavailable',
  'too-many-requests': 'too-many-requests',
  'topship-error': 'topship-error',
  'operation-not-allowed': 'operation-not-allowed',
  'conflict-error': 'conflict-error',
  'integration-error': 'integration-error',
  'identity-pass-error': 'identity-pass-error',
  'providus-third-party-error': 'providus-third-party-error',
  'request-accepted': 'request-accepted',
} as const;
