/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedCardTransaction } from './apiHydratedCardTransaction';
import type { ResponseWrapperApiHydratedCardTransactionCode } from './responseWrapperApiHydratedCardTransactionCode';

export interface ResponseWrapperApiHydratedCardTransaction {
  code: ResponseWrapperApiHydratedCardTransactionCode;
  message?: string;
  /** Response data */
  data: ApiHydratedCardTransaction;
}
