/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { ApiHydratedEvent } from './apiHydratedEvent';
import type { ResponseWrapperApiHydratedEventCode } from './responseWrapperApiHydratedEventCode';

export interface ResponseWrapperApiHydratedEvent {
  code: ResponseWrapperApiHydratedEventCode;
  message?: string;
  /** Response data */
  data: ApiHydratedEvent;
}
