/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface ShippingAddress {
  /** City */
  city: string;
  /** State */
  state: string;
  /** Country code */
  countryCode: string;
  /** Phone number */
  phoneNumber: string;
  /** Address line one */
  addressLineOne: string;
  /** Address line two */
  addressLineTwo?: string;
}
