/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { SimulateCardCaptureDtoChannel } from './simulateCardCaptureDtoChannel';

export interface SimulateCardCaptureDto {
  /** Amount to be debited from the card */
  amount: number;
  /** Fees to be debited from the card */
  fees: number;
  /** Channel of the transaction */
  channel: SimulateCardCaptureDtoChannel;
  /** MCC of the transaction */
  mcc?: string;
  /** Merchant Name Location */
  merchantDescriptor?: string;
}
