/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import type { SimulateCardCheckDtoChannel } from './simulateCardCheckDtoChannel';

export interface SimulateCardCheckDto {
  /** Channel of the transaction */
  channel: SimulateCardCheckDtoChannel;
  /** MCC of the transaction */
  mcc?: string;
  /** Merchant Name Location */
  merchantDescriptor?: string;
}
