/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface TeamInviteUserDto {
  /** Email address of the user to invite */
  email: string;
  /** List of role names to assign to the invited user */
  roles: string[];
}
