/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface TempFileUploadResult {
  /** Public URL of the uploaded file */
  url: string;
  /** Storage key of the uploaded file */
  keyName: string;
}
