/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export interface TreasuryFlowSplitStatDto {
  /** Flow label */
  name: string;
  /** Transaction count */
  count: number;
  /** Volume in lowest currency unit (kobo) */
  total: number;
  /** Share of total flow count (percent) */
  percent: number;
}
