/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */

export type WebhookDtoEventsItem = typeof WebhookDtoEventsItem[keyof typeof WebhookDtoEventsItem];


export const WebhookDtoEventsItem = {
  cardcreated: 'card.created',
  cardlinked: 'card.linked',
  cardactivated: 'card.activated',
  cardterminated: 'card.terminated',
  cardauthorizationrequest: 'card.authorization.request',
  cardauthorizationclosed: 'card.authorization.closed',
  cardauthorizationupdate: 'card.authorization.update',
  cardtransactioncreated: 'card.transaction.created',
  paymentcompleted: 'payment.completed',
  paymentauthorizationapproved: 'payment.authorization.approved',
  paymentauthorizationactivated: 'payment.authorization.activated',
  disputeupdated: 'dispute.updated',
  requestcompleted: 'request.completed',
  requestcancelled: 'request.cancelled',
} as const;
