/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccountControllerGetLogCSVParams,
  AccountControllerGetLogsParams,
  AccountControllerGetOneParams,
  AccountControllerGetParams,
  AccountControllerGetStatementPDFParams,
  AddDepositChannelDto,
  BasicResponse,
  CreateAccountDto,
  RequestOverdraftDto,
  ResponseWrapperApiHydratedAccount,
  ResponseWrapperApiHydratedAccountList
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get All Accounts
 */
export type accountControllerGetResponse200 = {
  data: ResponseWrapperApiHydratedAccountList
  status: 200
}

export type accountControllerGetResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerGetResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerGetResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerGetResponseSuccess = (accountControllerGetResponse200) & {
  headers: Headers;
};
export type accountControllerGetResponseError = (accountControllerGetResponse400 | accountControllerGetResponse401 | accountControllerGetResponse403) & {
  headers: Headers;
};

export type accountControllerGetResponse = (accountControllerGetResponseSuccess | accountControllerGetResponseError)

export const getAccountControllerGetUrl = (params?: AccountControllerGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/accounts?${stringifiedParams}` : `/accounts`
}

export const accountControllerGet = async (params?: AccountControllerGetParams, options?: RequestInit): Promise<accountControllerGetResponse> => {

  return customInstance<accountControllerGetResponse>(getAccountControllerGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetQueryKey = (params?: AccountControllerGetParams,) => {
    return [
    `/accounts`, ...(params ? [params] : [])
    ] as const;
    }


export const getAccountControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<BasicResponse>>(params?: AccountControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGet>>> = ({ signal }) => accountControllerGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGet>>>
export type AccountControllerGetQueryError = ErrorType<BasicResponse>


export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  AccountControllerGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGet>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: AccountControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGet>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: AccountControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get All Accounts
 */

export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: AccountControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Account
 */
export type accountControllerCreateResponse201 = {
  data: ResponseWrapperApiHydratedAccount
  status: 201
}

export type accountControllerCreateResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerCreateResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerCreateResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerCreateResponseSuccess = (accountControllerCreateResponse201) & {
  headers: Headers;
};
export type accountControllerCreateResponseError = (accountControllerCreateResponse400 | accountControllerCreateResponse401 | accountControllerCreateResponse403) & {
  headers: Headers;
};

export type accountControllerCreateResponse = (accountControllerCreateResponseSuccess | accountControllerCreateResponseError)

export const getAccountControllerCreateUrl = () => {




  return `/accounts`
}

export const accountControllerCreate = async (createAccountDto: CreateAccountDto, options?: RequestInit): Promise<accountControllerCreateResponse> => {

  return customInstance<accountControllerCreateResponse>(getAccountControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAccountDto,)
  }
);}




export const getAccountControllerCreateMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerCreate>>, TError,{data: CreateAccountDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountControllerCreate>>, TError,{data: CreateAccountDto}, TContext> => {

const mutationKey = ['accountControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountControllerCreate>>, {data: CreateAccountDto}> = (props) => {
          const {data} = props ?? {};

          return  accountControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AccountControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof accountControllerCreate>>>
    export type AccountControllerCreateMutationBody = CreateAccountDto
    export type AccountControllerCreateMutationError = ErrorType<BasicResponse>

    /**
 * @summary Create Account
 */
export const useAccountControllerCreate = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerCreate>>, TError,{data: CreateAccountDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountControllerCreate>>,
        TError,
        {data: CreateAccountDto},
        TContext
      > => {
      return useMutation(getAccountControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get One Account
 */
export type accountControllerGetOneResponse200 = {
  data: ResponseWrapperApiHydratedAccount
  status: 200
}

export type accountControllerGetOneResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerGetOneResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerGetOneResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerGetOneResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerGetOneResponseSuccess = (accountControllerGetOneResponse200) & {
  headers: Headers;
};
export type accountControllerGetOneResponseError = (accountControllerGetOneResponse400 | accountControllerGetOneResponse401 | accountControllerGetOneResponse403 | accountControllerGetOneResponse404) & {
  headers: Headers;
};

export type accountControllerGetOneResponse = (accountControllerGetOneResponseSuccess | accountControllerGetOneResponseError)

export const getAccountControllerGetOneUrl = (id: string,
    params?: AccountControllerGetOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/accounts/${id}?${stringifiedParams}` : `/accounts/${id}`
}

export const accountControllerGetOne = async (id: string,
    params?: AccountControllerGetOneParams, options?: RequestInit): Promise<accountControllerGetOneResponse> => {

  return customInstance<accountControllerGetOneResponse>(getAccountControllerGetOneUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetOneQueryKey = (id: string,
    params?: AccountControllerGetOneParams,) => {
    return [
    `/accounts/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getAccountControllerGetOneQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: AccountControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetOneQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetOne>>> = ({ signal }) => accountControllerGetOne(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetOne>>>
export type AccountControllerGetOneQueryError = ErrorType<BasicResponse>


export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  AccountControllerGetOneParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get One Account
 */

export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetOneQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Account Balance
 */
export type accountControllerGetBalanceResponse200 = {
  data: BasicResponse
  status: 200
}

export type accountControllerGetBalanceResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerGetBalanceResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerGetBalanceResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerGetBalanceResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerGetBalanceResponseSuccess = (accountControllerGetBalanceResponse200) & {
  headers: Headers;
};
export type accountControllerGetBalanceResponseError = (accountControllerGetBalanceResponse400 | accountControllerGetBalanceResponse401 | accountControllerGetBalanceResponse403 | accountControllerGetBalanceResponse404) & {
  headers: Headers;
};

export type accountControllerGetBalanceResponse = (accountControllerGetBalanceResponseSuccess | accountControllerGetBalanceResponseError)

export const getAccountControllerGetBalanceUrl = (id: string,) => {




  return `/accounts/${id}/balance`
}

export const accountControllerGetBalance = async (id: string, options?: RequestInit): Promise<accountControllerGetBalanceResponse> => {

  return customInstance<accountControllerGetBalanceResponse>(getAccountControllerGetBalanceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetBalanceQueryKey = (id: string,) => {
    return [
    `/accounts/${id}/balance`
    ] as const;
    }


export const getAccountControllerGetBalanceQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<BasicResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetBalanceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetBalance>>> = ({ signal }) => accountControllerGetBalance(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetBalance>>>
export type AccountControllerGetBalanceQueryError = ErrorType<BasicResponse>


export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<BasicResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetBalance>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetBalance>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Account Balance
 */

export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetBalanceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Request Credit Limit Approval
 */
export type accountControllerRequestCreditLimitApprovalResponse200 = {
  data: BasicResponse
  status: 200
}

export type accountControllerRequestCreditLimitApprovalResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerRequestCreditLimitApprovalResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerRequestCreditLimitApprovalResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerRequestCreditLimitApprovalResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerRequestCreditLimitApprovalResponseSuccess = (accountControllerRequestCreditLimitApprovalResponse200) & {
  headers: Headers;
};
export type accountControllerRequestCreditLimitApprovalResponseError = (accountControllerRequestCreditLimitApprovalResponse400 | accountControllerRequestCreditLimitApprovalResponse401 | accountControllerRequestCreditLimitApprovalResponse403 | accountControllerRequestCreditLimitApprovalResponse404) & {
  headers: Headers;
};

export type accountControllerRequestCreditLimitApprovalResponse = (accountControllerRequestCreditLimitApprovalResponseSuccess | accountControllerRequestCreditLimitApprovalResponseError)

export const getAccountControllerRequestCreditLimitApprovalUrl = (id: string,) => {




  return `/accounts/${id}/credit-limit`
}

export const accountControllerRequestCreditLimitApproval = async (id: string,
    requestOverdraftDto: RequestOverdraftDto, options?: RequestInit): Promise<accountControllerRequestCreditLimitApprovalResponse> => {

  return customInstance<accountControllerRequestCreditLimitApprovalResponse>(getAccountControllerRequestCreditLimitApprovalUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestOverdraftDto,)
  }
);}




export const getAccountControllerRequestCreditLimitApprovalMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, TError,{id: string;data: RequestOverdraftDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, TError,{id: string;data: RequestOverdraftDto}, TContext> => {

const mutationKey = ['accountControllerRequestCreditLimitApproval'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, {id: string;data: RequestOverdraftDto}> = (props) => {
          const {id,data} = props ?? {};

          return  accountControllerRequestCreditLimitApproval(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AccountControllerRequestCreditLimitApprovalMutationResult = NonNullable<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>>
    export type AccountControllerRequestCreditLimitApprovalMutationBody = RequestOverdraftDto
    export type AccountControllerRequestCreditLimitApprovalMutationError = ErrorType<BasicResponse>

    /**
 * @summary Request Credit Limit Approval
 */
export const useAccountControllerRequestCreditLimitApproval = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, TError,{id: string;data: RequestOverdraftDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>,
        TError,
        {id: string;data: RequestOverdraftDto},
        TContext
      > => {
      return useMutation(getAccountControllerRequestCreditLimitApprovalMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Balance History
 */
export type accountControllerGetLogsResponse200 = {
  data: BasicResponse
  status: 200
}

export type accountControllerGetLogsResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerGetLogsResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerGetLogsResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerGetLogsResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerGetLogsResponseSuccess = (accountControllerGetLogsResponse200) & {
  headers: Headers;
};
export type accountControllerGetLogsResponseError = (accountControllerGetLogsResponse400 | accountControllerGetLogsResponse401 | accountControllerGetLogsResponse403 | accountControllerGetLogsResponse404) & {
  headers: Headers;
};

export type accountControllerGetLogsResponse = (accountControllerGetLogsResponseSuccess | accountControllerGetLogsResponseError)

export const getAccountControllerGetLogsUrl = (id: string,
    params?: AccountControllerGetLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/accounts/${id}/balance/history?${stringifiedParams}` : `/accounts/${id}/balance/history`
}

export const accountControllerGetLogs = async (id: string,
    params?: AccountControllerGetLogsParams, options?: RequestInit): Promise<accountControllerGetLogsResponse> => {

  return customInstance<accountControllerGetLogsResponse>(getAccountControllerGetLogsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetLogsQueryKey = (id: string,
    params?: AccountControllerGetLogsParams,) => {
    return [
    `/accounts/${id}/balance/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getAccountControllerGetLogsQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: AccountControllerGetLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetLogsQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetLogs>>> = ({ signal }) => accountControllerGetLogs(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetLogsQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetLogs>>>
export type AccountControllerGetLogsQueryError = ErrorType<BasicResponse>


export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  AccountControllerGetLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogs>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogs>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Balance History
 */

export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetLogsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download Balance History CSV
 */
export type accountControllerGetLogCSVResponse200 = {
  data: BasicResponse
  status: 200
}

export type accountControllerGetLogCSVResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerGetLogCSVResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerGetLogCSVResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerGetLogCSVResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerGetLogCSVResponseSuccess = (accountControllerGetLogCSVResponse200) & {
  headers: Headers;
};
export type accountControllerGetLogCSVResponseError = (accountControllerGetLogCSVResponse400 | accountControllerGetLogCSVResponse401 | accountControllerGetLogCSVResponse403 | accountControllerGetLogCSVResponse404) & {
  headers: Headers;
};

export type accountControllerGetLogCSVResponse = (accountControllerGetLogCSVResponseSuccess | accountControllerGetLogCSVResponseError)

export const getAccountControllerGetLogCSVUrl = (id: string,
    params?: AccountControllerGetLogCSVParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/accounts/${id}/balance/history/csv?${stringifiedParams}` : `/accounts/${id}/balance/history/csv`
}

export const accountControllerGetLogCSV = async (id: string,
    params?: AccountControllerGetLogCSVParams, options?: RequestInit): Promise<accountControllerGetLogCSVResponse> => {

  return customInstance<accountControllerGetLogCSVResponse>(getAccountControllerGetLogCSVUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetLogCSVQueryKey = (id: string,
    params?: AccountControllerGetLogCSVParams,) => {
    return [
    `/accounts/${id}/balance/history/csv`, ...(params ? [params] : [])
    ] as const;
    }


export const getAccountControllerGetLogCSVQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: AccountControllerGetLogCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetLogCSVQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetLogCSV>>> = ({ signal }) => accountControllerGetLogCSV(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetLogCSVQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetLogCSV>>>
export type AccountControllerGetLogCSVQueryError = ErrorType<BasicResponse>


export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  AccountControllerGetLogCSVParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetLogCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetLogCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Balance History CSV
 */

export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetLogCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetLogCSVQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download Statement PDF
 */
export type accountControllerGetStatementPDFResponse200 = {
  data: BasicResponse
  status: 200
}

export type accountControllerGetStatementPDFResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerGetStatementPDFResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerGetStatementPDFResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerGetStatementPDFResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerGetStatementPDFResponseSuccess = (accountControllerGetStatementPDFResponse200) & {
  headers: Headers;
};
export type accountControllerGetStatementPDFResponseError = (accountControllerGetStatementPDFResponse400 | accountControllerGetStatementPDFResponse401 | accountControllerGetStatementPDFResponse403 | accountControllerGetStatementPDFResponse404) & {
  headers: Headers;
};

export type accountControllerGetStatementPDFResponse = (accountControllerGetStatementPDFResponseSuccess | accountControllerGetStatementPDFResponseError)

export const getAccountControllerGetStatementPDFUrl = (id: string,
    params?: AccountControllerGetStatementPDFParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/accounts/${id}/statement/pdf?${stringifiedParams}` : `/accounts/${id}/statement/pdf`
}

export const accountControllerGetStatementPDF = async (id: string,
    params?: AccountControllerGetStatementPDFParams, options?: RequestInit): Promise<accountControllerGetStatementPDFResponse> => {

  return customInstance<accountControllerGetStatementPDFResponse>(getAccountControllerGetStatementPDFUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetStatementPDFQueryKey = (id: string,
    params?: AccountControllerGetStatementPDFParams,) => {
    return [
    `/accounts/${id}/statement/pdf`, ...(params ? [params] : [])
    ] as const;
    }


export const getAccountControllerGetStatementPDFQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: AccountControllerGetStatementPDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetStatementPDFQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>> = ({ signal }) => accountControllerGetStatementPDF(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetStatementPDFQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>>
export type AccountControllerGetStatementPDFQueryError = ErrorType<BasicResponse>


export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  AccountControllerGetStatementPDFParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetStatementPDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetStatementPDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Statement PDF
 */

export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: AccountControllerGetStatementPDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetStatementPDFQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add Deposit Channel
 */
export type accountControllerAddDepositChannelResponse201 = {
  data: BasicResponse
  status: 201
}

export type accountControllerAddDepositChannelResponse400 = {
  data: BasicResponse
  status: 400
}

export type accountControllerAddDepositChannelResponse401 = {
  data: BasicResponse
  status: 401
}

export type accountControllerAddDepositChannelResponse403 = {
  data: BasicResponse
  status: 403
}

export type accountControllerAddDepositChannelResponse404 = {
  data: BasicResponse
  status: 404
}

export type accountControllerAddDepositChannelResponseSuccess = (accountControllerAddDepositChannelResponse201) & {
  headers: Headers;
};
export type accountControllerAddDepositChannelResponseError = (accountControllerAddDepositChannelResponse400 | accountControllerAddDepositChannelResponse401 | accountControllerAddDepositChannelResponse403 | accountControllerAddDepositChannelResponse404) & {
  headers: Headers;
};

export type accountControllerAddDepositChannelResponse = (accountControllerAddDepositChannelResponseSuccess | accountControllerAddDepositChannelResponseError)

export const getAccountControllerAddDepositChannelUrl = (id: string,) => {




  return `/accounts/${id}/deposit-channels`
}

export const accountControllerAddDepositChannel = async (id: string,
    addDepositChannelDto: AddDepositChannelDto, options?: RequestInit): Promise<accountControllerAddDepositChannelResponse> => {

  return customInstance<accountControllerAddDepositChannelResponse>(getAccountControllerAddDepositChannelUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addDepositChannelDto,)
  }
);}




export const getAccountControllerAddDepositChannelMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, TError,{id: string;data: AddDepositChannelDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, TError,{id: string;data: AddDepositChannelDto}, TContext> => {

const mutationKey = ['accountControllerAddDepositChannel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, {id: string;data: AddDepositChannelDto}> = (props) => {
          const {id,data} = props ?? {};

          return  accountControllerAddDepositChannel(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AccountControllerAddDepositChannelMutationResult = NonNullable<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>>
    export type AccountControllerAddDepositChannelMutationBody = AddDepositChannelDto
    export type AccountControllerAddDepositChannelMutationError = ErrorType<BasicResponse>

    /**
 * @summary Add Deposit Channel
 */
export const useAccountControllerAddDepositChannel = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, TError,{id: string;data: AddDepositChannelDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountControllerAddDepositChannel>>,
        TError,
        {id: string;data: AddDepositChannelDto},
        TContext
      > => {
      return useMutation(getAccountControllerAddDepositChannelMutationOptions(options), queryClient);
    }
