/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RequestOverdraftDto
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get All Accounts
 */
export type accountControllerGetResponse200 = {
  data: void
  status: 200
}

export type accountControllerGetResponseSuccess = (accountControllerGetResponse200) & {
  headers: Headers;
};
;

export type accountControllerGetResponse = (accountControllerGetResponseSuccess)

export const getAccountControllerGetUrl = () => {




  return `/accounts`
}

export const accountControllerGet = async ( options?: RequestInit): Promise<accountControllerGetResponse> => {

  return customInstance<accountControllerGetResponse>(getAccountControllerGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetQueryKey = () => {
    return [
    `/accounts`
    ] as const;
    }


export const getAccountControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGet>>> = ({ signal }) => accountControllerGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGet>>>
export type AccountControllerGetQueryError = ErrorType<unknown>


export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGet>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGet>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get All Accounts
 */

export function useAccountControllerGet<TData = Awaited<ReturnType<typeof accountControllerGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Accounts
 */
export type accountControllerCreateResponse201 = {
  data: void
  status: 201
}

export type accountControllerCreateResponseSuccess = (accountControllerCreateResponse201) & {
  headers: Headers;
};
;

export type accountControllerCreateResponse = (accountControllerCreateResponseSuccess)

export const getAccountControllerCreateUrl = () => {




  return `/accounts`
}

export const accountControllerCreate = async ( options?: RequestInit): Promise<accountControllerCreateResponse> => {

  return customInstance<accountControllerCreateResponse>(getAccountControllerCreateUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAccountControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['accountControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountControllerCreate>>, void> = () => {


          return  accountControllerCreate(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AccountControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof accountControllerCreate>>>

    export type AccountControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary Create Accounts
 */
export const useAccountControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountControllerCreate>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAccountControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get One Account
 */
export type accountControllerGetOneResponse200 = {
  data: void
  status: 200
}

export type accountControllerGetOneResponseSuccess = (accountControllerGetOneResponse200) & {
  headers: Headers;
};
;

export type accountControllerGetOneResponse = (accountControllerGetOneResponseSuccess)

export const getAccountControllerGetOneUrl = (id: string,) => {




  return `/accounts/${id}`
}

export const accountControllerGetOne = async (id: string, options?: RequestInit): Promise<accountControllerGetOneResponse> => {

  return customInstance<accountControllerGetOneResponse>(getAccountControllerGetOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetOneQueryKey = (id: string,) => {
    return [
    `/accounts/${id}`
    ] as const;
    }


export const getAccountControllerGetOneQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetOne>>> = ({ signal }) => accountControllerGetOne(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetOne>>>
export type AccountControllerGetOneQueryError = ErrorType<unknown>


export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get One Account
 */

export function useAccountControllerGetOne<TData = Awaited<ReturnType<typeof accountControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Account Balance
 */
export type accountControllerGetBalanceResponse200 = {
  data: void
  status: 200
}

export type accountControllerGetBalanceResponseSuccess = (accountControllerGetBalanceResponse200) & {
  headers: Headers;
};
;

export type accountControllerGetBalanceResponse = (accountControllerGetBalanceResponseSuccess)

export const getAccountControllerGetBalanceUrl = (id: string,) => {




  return `/accounts/${id}/balance`
}

export const accountControllerGetBalance = async (id: string, options?: RequestInit): Promise<accountControllerGetBalanceResponse> => {

  return customInstance<accountControllerGetBalanceResponse>(getAccountControllerGetBalanceUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetBalanceQueryKey = (id: string,) => {
    return [
    `/accounts/${id}/balance`
    ] as const;
    }


export const getAccountControllerGetBalanceQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetBalanceQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetBalance>>> = ({ signal }) => accountControllerGetBalance(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetBalance>>>
export type AccountControllerGetBalanceQueryError = ErrorType<unknown>


export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetBalance>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetBalance>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Account Balance
 */

export function useAccountControllerGetBalance<TData = Awaited<ReturnType<typeof accountControllerGetBalance>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetBalanceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Request Credit Limit Approval
 */
export type accountControllerRequestCreditLimitApprovalResponse201 = {
  data: void
  status: 201
}

export type accountControllerRequestCreditLimitApprovalResponseSuccess = (accountControllerRequestCreditLimitApprovalResponse201) & {
  headers: Headers;
};
;

export type accountControllerRequestCreditLimitApprovalResponse = (accountControllerRequestCreditLimitApprovalResponseSuccess)

export const getAccountControllerRequestCreditLimitApprovalUrl = (id: string,) => {




  return `/accounts/${id}/credit-limit`
}

export const accountControllerRequestCreditLimitApproval = async (id: string,
    requestOverdraftDto: RequestOverdraftDto, options?: RequestInit): Promise<accountControllerRequestCreditLimitApprovalResponse> => {

  return customInstance<accountControllerRequestCreditLimitApprovalResponse>(getAccountControllerRequestCreditLimitApprovalUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestOverdraftDto,)
  }
);}




export const getAccountControllerRequestCreditLimitApprovalMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, TError,{id: string;data: RequestOverdraftDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, TError,{id: string;data: RequestOverdraftDto}, TContext> => {

const mutationKey = ['accountControllerRequestCreditLimitApproval'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, {id: string;data: RequestOverdraftDto}> = (props) => {
          const {id,data} = props ?? {};

          return  accountControllerRequestCreditLimitApproval(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AccountControllerRequestCreditLimitApprovalMutationResult = NonNullable<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>>
    export type AccountControllerRequestCreditLimitApprovalMutationBody = RequestOverdraftDto
    export type AccountControllerRequestCreditLimitApprovalMutationError = ErrorType<unknown>

    /**
 * @summary Request Credit Limit Approval
 */
export const useAccountControllerRequestCreditLimitApproval = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>, TError,{id: string;data: RequestOverdraftDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountControllerRequestCreditLimitApproval>>,
        TError,
        {id: string;data: RequestOverdraftDto},
        TContext
      > => {
      return useMutation(getAccountControllerRequestCreditLimitApprovalMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Balance Log
 */
export type accountControllerGetLogsResponse200 = {
  data: void
  status: 200
}

export type accountControllerGetLogsResponseSuccess = (accountControllerGetLogsResponse200) & {
  headers: Headers;
};
;

export type accountControllerGetLogsResponse = (accountControllerGetLogsResponseSuccess)

export const getAccountControllerGetLogsUrl = (id: string,) => {




  return `/accounts/${id}/balance/history`
}

export const accountControllerGetLogs = async (id: string, options?: RequestInit): Promise<accountControllerGetLogsResponse> => {

  return customInstance<accountControllerGetLogsResponse>(getAccountControllerGetLogsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetLogsQueryKey = (id: string,) => {
    return [
    `/accounts/${id}/balance/history`
    ] as const;
    }


export const getAccountControllerGetLogsQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetLogsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetLogs>>> = ({ signal }) => accountControllerGetLogs(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetLogsQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetLogs>>>
export type AccountControllerGetLogsQueryError = ErrorType<unknown>


export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogs>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogs>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Balance Log
 */

export function useAccountControllerGetLogs<TData = Awaited<ReturnType<typeof accountControllerGetLogs>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetLogsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Balance Log in CSV
 */
export type accountControllerGetLogCSVResponse200 = {
  data: void
  status: 200
}

export type accountControllerGetLogCSVResponseSuccess = (accountControllerGetLogCSVResponse200) & {
  headers: Headers;
};
;

export type accountControllerGetLogCSVResponse = (accountControllerGetLogCSVResponseSuccess)

export const getAccountControllerGetLogCSVUrl = (id: string,) => {




  return `/accounts/${id}/balance/history/csv`
}

export const accountControllerGetLogCSV = async (id: string, options?: RequestInit): Promise<accountControllerGetLogCSVResponse> => {

  return customInstance<accountControllerGetLogCSVResponse>(getAccountControllerGetLogCSVUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetLogCSVQueryKey = (id: string,) => {
    return [
    `/accounts/${id}/balance/history/csv`
    ] as const;
    }


export const getAccountControllerGetLogCSVQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetLogCSVQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetLogCSV>>> = ({ signal }) => accountControllerGetLogCSV(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetLogCSVQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetLogCSV>>>
export type AccountControllerGetLogCSVQueryError = ErrorType<unknown>


export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetLogCSV>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Balance Log in CSV
 */

export function useAccountControllerGetLogCSV<TData = Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetLogCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetLogCSVQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download Statement in PDF
 */
export type accountControllerGetStatementPDFResponse200 = {
  data: void
  status: 200
}

export type accountControllerGetStatementPDFResponseSuccess = (accountControllerGetStatementPDFResponse200) & {
  headers: Headers;
};
;

export type accountControllerGetStatementPDFResponse = (accountControllerGetStatementPDFResponseSuccess)

export const getAccountControllerGetStatementPDFUrl = (id: string,) => {




  return `/accounts/${id}/statement/pdf`
}

export const accountControllerGetStatementPDF = async (id: string, options?: RequestInit): Promise<accountControllerGetStatementPDFResponse> => {

  return customInstance<accountControllerGetStatementPDFResponse>(getAccountControllerGetStatementPDFUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAccountControllerGetStatementPDFQueryKey = (id: string,) => {
    return [
    `/accounts/${id}/statement/pdf`
    ] as const;
    }


export const getAccountControllerGetStatementPDFQueryOptions = <TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccountControllerGetStatementPDFQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>> = ({ signal }) => accountControllerGetStatementPDF(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccountControllerGetStatementPDFQueryResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>>
export type AccountControllerGetStatementPDFQueryError = ErrorType<unknown>


export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetStatementPDF>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Statement in PDF
 */

export function useAccountControllerGetStatementPDF<TData = Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accountControllerGetStatementPDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccountControllerGetStatementPDFQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add Deposit Channel
 */
export type accountControllerAddDepositChannelResponse201 = {
  data: void
  status: 201
}

export type accountControllerAddDepositChannelResponseSuccess = (accountControllerAddDepositChannelResponse201) & {
  headers: Headers;
};
;

export type accountControllerAddDepositChannelResponse = (accountControllerAddDepositChannelResponseSuccess)

export const getAccountControllerAddDepositChannelUrl = (id: string,) => {




  return `/accounts/${id}/deposit-channels`
}

export const accountControllerAddDepositChannel = async (id: string, options?: RequestInit): Promise<accountControllerAddDepositChannelResponse> => {

  return customInstance<accountControllerAddDepositChannelResponse>(getAccountControllerAddDepositChannelUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAccountControllerAddDepositChannelMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, TError,{id: string}, TContext> => {

const mutationKey = ['accountControllerAddDepositChannel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  accountControllerAddDepositChannel(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AccountControllerAddDepositChannelMutationResult = NonNullable<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>>

    export type AccountControllerAddDepositChannelMutationError = ErrorType<unknown>

    /**
 * @summary Add Deposit Channel
 */
export const useAccountControllerAddDepositChannel = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountControllerAddDepositChannel>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof accountControllerAddDepositChannel>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getAccountControllerAddDepositChannelMutationOptions(options), queryClient);
    }
