/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BasicResponse,
  KYCBusinessAddressDto,
  KYCBusinessInformationDto,
  KYCLeadershipDto,
  ResponseWrapperApiHydratedBusinessKYC,
  ResponseWrapperApiHydratedBusinessLeadership
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create KYC submission
 */
export type businessKYCControllerCreateKYCResponse201 = {
  data: ResponseWrapperApiHydratedBusinessKYC
  status: 201
}

export type businessKYCControllerCreateKYCResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerCreateKYCResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerCreateKYCResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerCreateKYCResponseSuccess = (businessKYCControllerCreateKYCResponse201) & {
  headers: Headers;
};
export type businessKYCControllerCreateKYCResponseError = (businessKYCControllerCreateKYCResponse400 | businessKYCControllerCreateKYCResponse401 | businessKYCControllerCreateKYCResponse403) & {
  headers: Headers;
};

export type businessKYCControllerCreateKYCResponse = (businessKYCControllerCreateKYCResponseSuccess | businessKYCControllerCreateKYCResponseError)

export const getBusinessKYCControllerCreateKYCUrl = () => {




  return `/business/kyc`
}

export const businessKYCControllerCreateKYC = async (kYCBusinessInformationDto: KYCBusinessInformationDto, options?: RequestInit): Promise<businessKYCControllerCreateKYCResponse> => {

  return customInstance<businessKYCControllerCreateKYCResponse>(getBusinessKYCControllerCreateKYCUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kYCBusinessInformationDto,)
  }
);}




export const getBusinessKYCControllerCreateKYCMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerCreateKYC>>, TError,{data: KYCBusinessInformationDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerCreateKYC>>, TError,{data: KYCBusinessInformationDto}, TContext> => {

const mutationKey = ['businessKYCControllerCreateKYC'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerCreateKYC>>, {data: KYCBusinessInformationDto}> = (props) => {
          const {data} = props ?? {};

          return  businessKYCControllerCreateKYC(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerCreateKYCMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerCreateKYC>>>
    export type BusinessKYCControllerCreateKYCMutationBody = KYCBusinessInformationDto
    export type BusinessKYCControllerCreateKYCMutationError = ErrorType<BasicResponse>

    /**
 * @summary Create KYC submission
 */
export const useBusinessKYCControllerCreateKYC = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerCreateKYC>>, TError,{data: KYCBusinessInformationDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerCreateKYC>>,
        TError,
        {data: KYCBusinessInformationDto},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerCreateKYCMutationOptions(options), queryClient);
    }
    /**
 * @summary Get KYC submission
 */
export type businessKYCControllerGetKycResponse200 = {
  data: ResponseWrapperApiHydratedBusinessKYC
  status: 200
}

export type businessKYCControllerGetKycResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerGetKycResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerGetKycResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerGetKycResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerGetKycResponseSuccess = (businessKYCControllerGetKycResponse200) & {
  headers: Headers;
};
export type businessKYCControllerGetKycResponseError = (businessKYCControllerGetKycResponse400 | businessKYCControllerGetKycResponse401 | businessKYCControllerGetKycResponse403 | businessKYCControllerGetKycResponse404) & {
  headers: Headers;
};

export type businessKYCControllerGetKycResponse = (businessKYCControllerGetKycResponseSuccess | businessKYCControllerGetKycResponseError)

export const getBusinessKYCControllerGetKycUrl = (id: string,) => {




  return `/business/kyc/${id}`
}

export const businessKYCControllerGetKyc = async (id: string, options?: RequestInit): Promise<businessKYCControllerGetKycResponse> => {

  return customInstance<businessKYCControllerGetKycResponse>(getBusinessKYCControllerGetKycUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBusinessKYCControllerGetKycQueryKey = (id: string,) => {
    return [
    `/business/kyc/${id}`
    ] as const;
    }


export const getBusinessKYCControllerGetKycQueryOptions = <TData = Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError = ErrorType<BasicResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBusinessKYCControllerGetKycQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>> = ({ signal }) => businessKYCControllerGetKyc(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BusinessKYCControllerGetKycQueryResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>>
export type BusinessKYCControllerGetKycQueryError = ErrorType<BasicResponse>


export function useBusinessKYCControllerGetKyc<TData = Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError = ErrorType<BasicResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessKYCControllerGetKyc>>,
          TError,
          Awaited<ReturnType<typeof businessKYCControllerGetKyc>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessKYCControllerGetKyc<TData = Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessKYCControllerGetKyc>>,
          TError,
          Awaited<ReturnType<typeof businessKYCControllerGetKyc>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessKYCControllerGetKyc<TData = Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get KYC submission
 */

export function useBusinessKYCControllerGetKyc<TData = Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessKYCControllerGetKyc>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBusinessKYCControllerGetKycQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update business information
 */
export type businessKYCControllerUpdateBusinessInfoResponse200 = {
  data: ResponseWrapperApiHydratedBusinessKYC
  status: 200
}

export type businessKYCControllerUpdateBusinessInfoResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerUpdateBusinessInfoResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerUpdateBusinessInfoResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerUpdateBusinessInfoResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerUpdateBusinessInfoResponseSuccess = (businessKYCControllerUpdateBusinessInfoResponse200) & {
  headers: Headers;
};
export type businessKYCControllerUpdateBusinessInfoResponseError = (businessKYCControllerUpdateBusinessInfoResponse400 | businessKYCControllerUpdateBusinessInfoResponse401 | businessKYCControllerUpdateBusinessInfoResponse403 | businessKYCControllerUpdateBusinessInfoResponse404) & {
  headers: Headers;
};

export type businessKYCControllerUpdateBusinessInfoResponse = (businessKYCControllerUpdateBusinessInfoResponseSuccess | businessKYCControllerUpdateBusinessInfoResponseError)

export const getBusinessKYCControllerUpdateBusinessInfoUrl = (id: string,) => {




  return `/business/kyc/${id}/info`
}

export const businessKYCControllerUpdateBusinessInfo = async (id: string,
    kYCBusinessInformationDto: KYCBusinessInformationDto, options?: RequestInit): Promise<businessKYCControllerUpdateBusinessInfoResponse> => {

  return customInstance<businessKYCControllerUpdateBusinessInfoResponse>(getBusinessKYCControllerUpdateBusinessInfoUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kYCBusinessInformationDto,)
  }
);}




export const getBusinessKYCControllerUpdateBusinessInfoMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessInfo>>, TError,{id: string;data: KYCBusinessInformationDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessInfo>>, TError,{id: string;data: KYCBusinessInformationDto}, TContext> => {

const mutationKey = ['businessKYCControllerUpdateBusinessInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessInfo>>, {id: string;data: KYCBusinessInformationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  businessKYCControllerUpdateBusinessInfo(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerUpdateBusinessInfoMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessInfo>>>
    export type BusinessKYCControllerUpdateBusinessInfoMutationBody = KYCBusinessInformationDto
    export type BusinessKYCControllerUpdateBusinessInfoMutationError = ErrorType<BasicResponse>

    /**
 * @summary Update business information
 */
export const useBusinessKYCControllerUpdateBusinessInfo = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessInfo>>, TError,{id: string;data: KYCBusinessInformationDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessInfo>>,
        TError,
        {id: string;data: KYCBusinessInformationDto},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerUpdateBusinessInfoMutationOptions(options), queryClient);
    }
    /**
 * @summary Update business address
 */
export type businessKYCControllerUpdateBusinessAddressResponse200 = {
  data: ResponseWrapperApiHydratedBusinessKYC
  status: 200
}

export type businessKYCControllerUpdateBusinessAddressResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerUpdateBusinessAddressResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerUpdateBusinessAddressResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerUpdateBusinessAddressResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerUpdateBusinessAddressResponseSuccess = (businessKYCControllerUpdateBusinessAddressResponse200) & {
  headers: Headers;
};
export type businessKYCControllerUpdateBusinessAddressResponseError = (businessKYCControllerUpdateBusinessAddressResponse400 | businessKYCControllerUpdateBusinessAddressResponse401 | businessKYCControllerUpdateBusinessAddressResponse403 | businessKYCControllerUpdateBusinessAddressResponse404) & {
  headers: Headers;
};

export type businessKYCControllerUpdateBusinessAddressResponse = (businessKYCControllerUpdateBusinessAddressResponseSuccess | businessKYCControllerUpdateBusinessAddressResponseError)

export const getBusinessKYCControllerUpdateBusinessAddressUrl = (id: string,) => {




  return `/business/kyc/${id}/address`
}

export const businessKYCControllerUpdateBusinessAddress = async (id: string,
    kYCBusinessAddressDto: KYCBusinessAddressDto, options?: RequestInit): Promise<businessKYCControllerUpdateBusinessAddressResponse> => {

  return customInstance<businessKYCControllerUpdateBusinessAddressResponse>(getBusinessKYCControllerUpdateBusinessAddressUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kYCBusinessAddressDto,)
  }
);}




export const getBusinessKYCControllerUpdateBusinessAddressMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessAddress>>, TError,{id: string;data: KYCBusinessAddressDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessAddress>>, TError,{id: string;data: KYCBusinessAddressDto}, TContext> => {

const mutationKey = ['businessKYCControllerUpdateBusinessAddress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessAddress>>, {id: string;data: KYCBusinessAddressDto}> = (props) => {
          const {id,data} = props ?? {};

          return  businessKYCControllerUpdateBusinessAddress(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerUpdateBusinessAddressMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessAddress>>>
    export type BusinessKYCControllerUpdateBusinessAddressMutationBody = KYCBusinessAddressDto
    export type BusinessKYCControllerUpdateBusinessAddressMutationError = ErrorType<BasicResponse>

    /**
 * @summary Update business address
 */
export const useBusinessKYCControllerUpdateBusinessAddress = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessAddress>>, TError,{id: string;data: KYCBusinessAddressDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerUpdateBusinessAddress>>,
        TError,
        {id: string;data: KYCBusinessAddressDto},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerUpdateBusinessAddressMutationOptions(options), queryClient);
    }
    /**
 * @summary Add leadership member
 */
export type businessKYCControllerAddLeadershipResponse201 = {
  data: ResponseWrapperApiHydratedBusinessLeadership
  status: 201
}

export type businessKYCControllerAddLeadershipResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerAddLeadershipResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerAddLeadershipResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerAddLeadershipResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerAddLeadershipResponseSuccess = (businessKYCControllerAddLeadershipResponse201) & {
  headers: Headers;
};
export type businessKYCControllerAddLeadershipResponseError = (businessKYCControllerAddLeadershipResponse400 | businessKYCControllerAddLeadershipResponse401 | businessKYCControllerAddLeadershipResponse403 | businessKYCControllerAddLeadershipResponse404) & {
  headers: Headers;
};

export type businessKYCControllerAddLeadershipResponse = (businessKYCControllerAddLeadershipResponseSuccess | businessKYCControllerAddLeadershipResponseError)

export const getBusinessKYCControllerAddLeadershipUrl = (id: string,) => {




  return `/business/kyc/${id}/leadership`
}

export const businessKYCControllerAddLeadership = async (id: string,
    kYCLeadershipDto: KYCLeadershipDto, options?: RequestInit): Promise<businessKYCControllerAddLeadershipResponse> => {

  return customInstance<businessKYCControllerAddLeadershipResponse>(getBusinessKYCControllerAddLeadershipUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      kYCLeadershipDto,)
  }
);}




export const getBusinessKYCControllerAddLeadershipMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerAddLeadership>>, TError,{id: string;data: KYCLeadershipDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerAddLeadership>>, TError,{id: string;data: KYCLeadershipDto}, TContext> => {

const mutationKey = ['businessKYCControllerAddLeadership'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerAddLeadership>>, {id: string;data: KYCLeadershipDto}> = (props) => {
          const {id,data} = props ?? {};

          return  businessKYCControllerAddLeadership(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerAddLeadershipMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerAddLeadership>>>
    export type BusinessKYCControllerAddLeadershipMutationBody = KYCLeadershipDto
    export type BusinessKYCControllerAddLeadershipMutationError = ErrorType<BasicResponse>

    /**
 * @summary Add leadership member
 */
export const useBusinessKYCControllerAddLeadership = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerAddLeadership>>, TError,{id: string;data: KYCLeadershipDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerAddLeadership>>,
        TError,
        {id: string;data: KYCLeadershipDto},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerAddLeadershipMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete leadership member
 */
export type businessKYCControllerDeleteLeadershipResponse200 = {
  data: BasicResponse
  status: 200
}

export type businessKYCControllerDeleteLeadershipResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerDeleteLeadershipResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerDeleteLeadershipResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerDeleteLeadershipResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerDeleteLeadershipResponseSuccess = (businessKYCControllerDeleteLeadershipResponse200) & {
  headers: Headers;
};
export type businessKYCControllerDeleteLeadershipResponseError = (businessKYCControllerDeleteLeadershipResponse400 | businessKYCControllerDeleteLeadershipResponse401 | businessKYCControllerDeleteLeadershipResponse403 | businessKYCControllerDeleteLeadershipResponse404) & {
  headers: Headers;
};

export type businessKYCControllerDeleteLeadershipResponse = (businessKYCControllerDeleteLeadershipResponseSuccess | businessKYCControllerDeleteLeadershipResponseError)

export const getBusinessKYCControllerDeleteLeadershipUrl = (kycId: string,
    leadershipId: string,) => {




  return `/business/kyc/${kycId}/leadership/${leadershipId}`
}

export const businessKYCControllerDeleteLeadership = async (kycId: string,
    leadershipId: string, options?: RequestInit): Promise<businessKYCControllerDeleteLeadershipResponse> => {

  return customInstance<businessKYCControllerDeleteLeadershipResponse>(getBusinessKYCControllerDeleteLeadershipUrl(kycId,leadershipId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getBusinessKYCControllerDeleteLeadershipMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerDeleteLeadership>>, TError,{kycId: string;leadershipId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerDeleteLeadership>>, TError,{kycId: string;leadershipId: string}, TContext> => {

const mutationKey = ['businessKYCControllerDeleteLeadership'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerDeleteLeadership>>, {kycId: string;leadershipId: string}> = (props) => {
          const {kycId,leadershipId} = props ?? {};

          return  businessKYCControllerDeleteLeadership(kycId,leadershipId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerDeleteLeadershipMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerDeleteLeadership>>>

    export type BusinessKYCControllerDeleteLeadershipMutationError = ErrorType<BasicResponse>

    /**
 * @summary Delete leadership member
 */
export const useBusinessKYCControllerDeleteLeadership = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerDeleteLeadership>>, TError,{kycId: string;leadershipId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerDeleteLeadership>>,
        TError,
        {kycId: string;leadershipId: string},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerDeleteLeadershipMutationOptions(options), queryClient);
    }
    /**
 * @summary Add KYC documentation
 */
export type businessKYCControllerAddDocumentationsResponse201 = {
  data: ResponseWrapperApiHydratedBusinessKYC
  status: 201
}

export type businessKYCControllerAddDocumentationsResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerAddDocumentationsResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerAddDocumentationsResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerAddDocumentationsResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerAddDocumentationsResponseSuccess = (businessKYCControllerAddDocumentationsResponse201) & {
  headers: Headers;
};
export type businessKYCControllerAddDocumentationsResponseError = (businessKYCControllerAddDocumentationsResponse400 | businessKYCControllerAddDocumentationsResponse401 | businessKYCControllerAddDocumentationsResponse403 | businessKYCControllerAddDocumentationsResponse404) & {
  headers: Headers;
};

export type businessKYCControllerAddDocumentationsResponse = (businessKYCControllerAddDocumentationsResponseSuccess | businessKYCControllerAddDocumentationsResponseError)

export const getBusinessKYCControllerAddDocumentationsUrl = (id: string,) => {




  return `/business/kyc/${id}/documentation`
}

export const businessKYCControllerAddDocumentations = async (id: string, options?: RequestInit): Promise<businessKYCControllerAddDocumentationsResponse> => {

  return customInstance<businessKYCControllerAddDocumentationsResponse>(getBusinessKYCControllerAddDocumentationsUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getBusinessKYCControllerAddDocumentationsMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerAddDocumentations>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerAddDocumentations>>, TError,{id: string}, TContext> => {

const mutationKey = ['businessKYCControllerAddDocumentations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerAddDocumentations>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  businessKYCControllerAddDocumentations(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerAddDocumentationsMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerAddDocumentations>>>

    export type BusinessKYCControllerAddDocumentationsMutationError = ErrorType<BasicResponse>

    /**
 * @summary Add KYC documentation
 */
export const useBusinessKYCControllerAddDocumentations = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerAddDocumentations>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerAddDocumentations>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerAddDocumentationsMutationOptions(options), queryClient);
    }
    /**
 * @summary Update KYC documentation
 */
export type businessKYCControllerUpdateDocumentationsResponse200 = {
  data: ResponseWrapperApiHydratedBusinessKYC
  status: 200
}

export type businessKYCControllerUpdateDocumentationsResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerUpdateDocumentationsResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerUpdateDocumentationsResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerUpdateDocumentationsResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerUpdateDocumentationsResponseSuccess = (businessKYCControllerUpdateDocumentationsResponse200) & {
  headers: Headers;
};
export type businessKYCControllerUpdateDocumentationsResponseError = (businessKYCControllerUpdateDocumentationsResponse400 | businessKYCControllerUpdateDocumentationsResponse401 | businessKYCControllerUpdateDocumentationsResponse403 | businessKYCControllerUpdateDocumentationsResponse404) & {
  headers: Headers;
};

export type businessKYCControllerUpdateDocumentationsResponse = (businessKYCControllerUpdateDocumentationsResponseSuccess | businessKYCControllerUpdateDocumentationsResponseError)

export const getBusinessKYCControllerUpdateDocumentationsUrl = (id: string,) => {




  return `/business/kyc/${id}/documentation`
}

export const businessKYCControllerUpdateDocumentations = async (id: string, options?: RequestInit): Promise<businessKYCControllerUpdateDocumentationsResponse> => {

  return customInstance<businessKYCControllerUpdateDocumentationsResponse>(getBusinessKYCControllerUpdateDocumentationsUrl(id),
  {
    ...options,
    method: 'PUT'


  }
);}




export const getBusinessKYCControllerUpdateDocumentationsMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateDocumentations>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateDocumentations>>, TError,{id: string}, TContext> => {

const mutationKey = ['businessKYCControllerUpdateDocumentations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerUpdateDocumentations>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  businessKYCControllerUpdateDocumentations(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerUpdateDocumentationsMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerUpdateDocumentations>>>

    export type BusinessKYCControllerUpdateDocumentationsMutationError = ErrorType<BasicResponse>

    /**
 * @summary Update KYC documentation
 */
export const useBusinessKYCControllerUpdateDocumentations = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerUpdateDocumentations>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerUpdateDocumentations>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerUpdateDocumentationsMutationOptions(options), queryClient);
    }
    /**
 * @summary Submit KYC for review
 */
export type businessKYCControllerSubmitKycResponse200 = {
  data: BasicResponse
  status: 200
}

export type businessKYCControllerSubmitKycResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessKYCControllerSubmitKycResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessKYCControllerSubmitKycResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessKYCControllerSubmitKycResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessKYCControllerSubmitKycResponseSuccess = (businessKYCControllerSubmitKycResponse200) & {
  headers: Headers;
};
export type businessKYCControllerSubmitKycResponseError = (businessKYCControllerSubmitKycResponse400 | businessKYCControllerSubmitKycResponse401 | businessKYCControllerSubmitKycResponse403 | businessKYCControllerSubmitKycResponse404) & {
  headers: Headers;
};

export type businessKYCControllerSubmitKycResponse = (businessKYCControllerSubmitKycResponseSuccess | businessKYCControllerSubmitKycResponseError)

export const getBusinessKYCControllerSubmitKycUrl = (id: string,) => {




  return `/business/kyc/${id}/submit`
}

export const businessKYCControllerSubmitKyc = async (id: string, options?: RequestInit): Promise<businessKYCControllerSubmitKycResponse> => {

  return customInstance<businessKYCControllerSubmitKycResponse>(getBusinessKYCControllerSubmitKycUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getBusinessKYCControllerSubmitKycMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerSubmitKyc>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerSubmitKyc>>, TError,{id: string}, TContext> => {

const mutationKey = ['businessKYCControllerSubmitKyc'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessKYCControllerSubmitKyc>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  businessKYCControllerSubmitKyc(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessKYCControllerSubmitKycMutationResult = NonNullable<Awaited<ReturnType<typeof businessKYCControllerSubmitKyc>>>

    export type BusinessKYCControllerSubmitKycMutationError = ErrorType<BasicResponse>

    /**
 * @summary Submit KYC for review
 */
export const useBusinessKYCControllerSubmitKyc = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessKYCControllerSubmitKyc>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessKYCControllerSubmitKyc>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBusinessKYCControllerSubmitKycMutationOptions(options), queryClient);
    }
