/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BasicResponse,
  PatchWebhookDto,
  ResponseWrapperApiHydratedWebhook,
  ResponseWrapperApiHydratedWebhookList,
  RollSecretWebhookDto,
  WebhookControllerGetOneParams,
  WebhookControllerGetParams,
  WebhookDto
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Webhooks
 */
export type webhookControllerGetResponse200 = {
  data: ResponseWrapperApiHydratedWebhookList
  status: 200
}

export type webhookControllerGetResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerGetResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerGetResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerGetResponseSuccess = (webhookControllerGetResponse200) & {
  headers: Headers;
};
export type webhookControllerGetResponseError = (webhookControllerGetResponse400 | webhookControllerGetResponse401 | webhookControllerGetResponse403) & {
  headers: Headers;
};

export type webhookControllerGetResponse = (webhookControllerGetResponseSuccess | webhookControllerGetResponseError)

export const getWebhookControllerGetUrl = (params?: WebhookControllerGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/webhooks?${stringifiedParams}` : `/webhooks`
}

export const webhookControllerGet = async (params?: WebhookControllerGetParams, options?: RequestInit): Promise<webhookControllerGetResponse> => {

  return customInstance<webhookControllerGetResponse>(getWebhookControllerGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWebhookControllerGetQueryKey = (params?: WebhookControllerGetParams,) => {
    return [
    `/webhooks`, ...(params ? [params] : [])
    ] as const;
    }


export const getWebhookControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof webhookControllerGet>>, TError = ErrorType<BasicResponse>>(params?: WebhookControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof webhookControllerGet>>> = ({ signal }) => webhookControllerGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebhookControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof webhookControllerGet>>>
export type WebhookControllerGetQueryError = ErrorType<BasicResponse>


export function useWebhookControllerGet<TData = Awaited<ReturnType<typeof webhookControllerGet>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  WebhookControllerGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhookControllerGet>>,
          TError,
          Awaited<ReturnType<typeof webhookControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhookControllerGet<TData = Awaited<ReturnType<typeof webhookControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: WebhookControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhookControllerGet>>,
          TError,
          Awaited<ReturnType<typeof webhookControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhookControllerGet<TData = Awaited<ReturnType<typeof webhookControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: WebhookControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Webhooks
 */

export function useWebhookControllerGet<TData = Awaited<ReturnType<typeof webhookControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: WebhookControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebhookControllerGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Webhooks
 */
export type webhookControllerCreateResponse201 = {
  data: ResponseWrapperApiHydratedWebhook
  status: 201
}

export type webhookControllerCreateResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerCreateResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerCreateResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerCreateResponseSuccess = (webhookControllerCreateResponse201) & {
  headers: Headers;
};
export type webhookControllerCreateResponseError = (webhookControllerCreateResponse400 | webhookControllerCreateResponse401 | webhookControllerCreateResponse403) & {
  headers: Headers;
};

export type webhookControllerCreateResponse = (webhookControllerCreateResponseSuccess | webhookControllerCreateResponseError)

export const getWebhookControllerCreateUrl = () => {




  return `/webhooks`
}

export const webhookControllerCreate = async (webhookDto: WebhookDto, options?: RequestInit): Promise<webhookControllerCreateResponse> => {

  return customInstance<webhookControllerCreateResponse>(getWebhookControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      webhookDto,)
  }
);}




export const getWebhookControllerCreateMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerCreate>>, TError,{data: WebhookDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerCreate>>, TError,{data: WebhookDto}, TContext> => {

const mutationKey = ['webhookControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerCreate>>, {data: WebhookDto}> = (props) => {
          const {data} = props ?? {};

          return  webhookControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerCreate>>>
    export type WebhookControllerCreateMutationBody = WebhookDto
    export type WebhookControllerCreateMutationError = ErrorType<BasicResponse>

    /**
 * @summary Create Webhooks
 */
export const useWebhookControllerCreate = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerCreate>>, TError,{data: WebhookDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerCreate>>,
        TError,
        {data: WebhookDto},
        TContext
      > => {
      return useMutation(getWebhookControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get One Webhook
 */
export type webhookControllerGetOneResponse200 = {
  data: ResponseWrapperApiHydratedWebhook
  status: 200
}

export type webhookControllerGetOneResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerGetOneResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerGetOneResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerGetOneResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerGetOneResponseSuccess = (webhookControllerGetOneResponse200) & {
  headers: Headers;
};
export type webhookControllerGetOneResponseError = (webhookControllerGetOneResponse400 | webhookControllerGetOneResponse401 | webhookControllerGetOneResponse403 | webhookControllerGetOneResponse404) & {
  headers: Headers;
};

export type webhookControllerGetOneResponse = (webhookControllerGetOneResponseSuccess | webhookControllerGetOneResponseError)

export const getWebhookControllerGetOneUrl = (id: string,
    params?: WebhookControllerGetOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/webhooks/${id}?${stringifiedParams}` : `/webhooks/${id}`
}

export const webhookControllerGetOne = async (id: string,
    params?: WebhookControllerGetOneParams, options?: RequestInit): Promise<webhookControllerGetOneResponse> => {

  return customInstance<webhookControllerGetOneResponse>(getWebhookControllerGetOneUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWebhookControllerGetOneQueryKey = (id: string,
    params?: WebhookControllerGetOneParams,) => {
    return [
    `/webhooks/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getWebhookControllerGetOneQueryOptions = <TData = Awaited<ReturnType<typeof webhookControllerGetOne>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: WebhookControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerGetOneQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof webhookControllerGetOne>>> = ({ signal }) => webhookControllerGetOne(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebhookControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof webhookControllerGetOne>>>
export type WebhookControllerGetOneQueryError = ErrorType<BasicResponse>


export function useWebhookControllerGetOne<TData = Awaited<ReturnType<typeof webhookControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  WebhookControllerGetOneParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhookControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof webhookControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhookControllerGetOne<TData = Awaited<ReturnType<typeof webhookControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: WebhookControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhookControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof webhookControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhookControllerGetOne<TData = Awaited<ReturnType<typeof webhookControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: WebhookControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get One Webhook
 */

export function useWebhookControllerGetOne<TData = Awaited<ReturnType<typeof webhookControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: WebhookControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebhookControllerGetOneQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Webhooks
 */
export type webhookControllerUpdateResponse200 = {
  data: ResponseWrapperApiHydratedWebhook
  status: 200
}

export type webhookControllerUpdateResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerUpdateResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerUpdateResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerUpdateResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerUpdateResponseSuccess = (webhookControllerUpdateResponse200) & {
  headers: Headers;
};
export type webhookControllerUpdateResponseError = (webhookControllerUpdateResponse400 | webhookControllerUpdateResponse401 | webhookControllerUpdateResponse403 | webhookControllerUpdateResponse404) & {
  headers: Headers;
};

export type webhookControllerUpdateResponse = (webhookControllerUpdateResponseSuccess | webhookControllerUpdateResponseError)

export const getWebhookControllerUpdateUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhookControllerUpdate = async (id: string,
    patchWebhookDto: PatchWebhookDto, options?: RequestInit): Promise<webhookControllerUpdateResponse> => {

  return customInstance<webhookControllerUpdateResponse>(getWebhookControllerUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchWebhookDto,)
  }
);}




export const getWebhookControllerUpdateMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerUpdate>>, TError,{id: string;data: PatchWebhookDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerUpdate>>, TError,{id: string;data: PatchWebhookDto}, TContext> => {

const mutationKey = ['webhookControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerUpdate>>, {id: string;data: PatchWebhookDto}> = (props) => {
          const {id,data} = props ?? {};

          return  webhookControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerUpdate>>>
    export type WebhookControllerUpdateMutationBody = PatchWebhookDto
    export type WebhookControllerUpdateMutationError = ErrorType<BasicResponse>

    /**
 * @summary Update Webhooks
 */
export const useWebhookControllerUpdate = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerUpdate>>, TError,{id: string;data: PatchWebhookDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerUpdate>>,
        TError,
        {id: string;data: PatchWebhookDto},
        TContext
      > => {
      return useMutation(getWebhookControllerUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Webhooks
 */
export type webhookControllerDeleteResponse200 = {
  data: BasicResponse
  status: 200
}

export type webhookControllerDeleteResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerDeleteResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerDeleteResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerDeleteResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerDeleteResponseSuccess = (webhookControllerDeleteResponse200) & {
  headers: Headers;
};
export type webhookControllerDeleteResponseError = (webhookControllerDeleteResponse400 | webhookControllerDeleteResponse401 | webhookControllerDeleteResponse403 | webhookControllerDeleteResponse404) & {
  headers: Headers;
};

export type webhookControllerDeleteResponse = (webhookControllerDeleteResponseSuccess | webhookControllerDeleteResponseError)

export const getWebhookControllerDeleteUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhookControllerDelete = async (id: string, options?: RequestInit): Promise<webhookControllerDeleteResponse> => {

  return customInstance<webhookControllerDeleteResponse>(getWebhookControllerDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getWebhookControllerDeleteMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['webhookControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  webhookControllerDelete(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerDelete>>>

    export type WebhookControllerDeleteMutationError = ErrorType<BasicResponse>

    /**
 * @summary Delete Webhooks
 */
export const useWebhookControllerDelete = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getWebhookControllerDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Webhook Signing Secret
 */
export type webhookControllerGetSigningSecretResponse200 = {
  data: BasicResponse
  status: 200
}

export type webhookControllerGetSigningSecretResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerGetSigningSecretResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerGetSigningSecretResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerGetSigningSecretResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerGetSigningSecretResponseSuccess = (webhookControllerGetSigningSecretResponse200) & {
  headers: Headers;
};
export type webhookControllerGetSigningSecretResponseError = (webhookControllerGetSigningSecretResponse400 | webhookControllerGetSigningSecretResponse401 | webhookControllerGetSigningSecretResponse403 | webhookControllerGetSigningSecretResponse404) & {
  headers: Headers;
};

export type webhookControllerGetSigningSecretResponse = (webhookControllerGetSigningSecretResponseSuccess | webhookControllerGetSigningSecretResponseError)

export const getWebhookControllerGetSigningSecretUrl = (id: string,) => {




  return `/webhooks/${id}/secret`
}

export const webhookControllerGetSigningSecret = async (id: string, options?: RequestInit): Promise<webhookControllerGetSigningSecretResponse> => {

  return customInstance<webhookControllerGetSigningSecretResponse>(getWebhookControllerGetSigningSecretUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWebhookControllerGetSigningSecretQueryKey = (id: string,) => {
    return [
    `/webhooks/${id}/secret`
    ] as const;
    }


export const getWebhookControllerGetSigningSecretQueryOptions = <TData = Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError = ErrorType<BasicResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWebhookControllerGetSigningSecretQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>> = ({ signal }) => webhookControllerGetSigningSecret(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WebhookControllerGetSigningSecretQueryResult = NonNullable<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>>
export type WebhookControllerGetSigningSecretQueryError = ErrorType<BasicResponse>


export function useWebhookControllerGetSigningSecret<TData = Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError = ErrorType<BasicResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>,
          TError,
          Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhookControllerGetSigningSecret<TData = Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>,
          TError,
          Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWebhookControllerGetSigningSecret<TData = Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Webhook Signing Secret
 */

export function useWebhookControllerGetSigningSecret<TData = Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof webhookControllerGetSigningSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWebhookControllerGetSigningSecretQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Roll Webhook Signing Secret
 */
export type webhookControllerRollSigningSecretResponse200 = {
  data: BasicResponse
  status: 200
}

export type webhookControllerRollSigningSecretResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerRollSigningSecretResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerRollSigningSecretResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerRollSigningSecretResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerRollSigningSecretResponseSuccess = (webhookControllerRollSigningSecretResponse200) & {
  headers: Headers;
};
export type webhookControllerRollSigningSecretResponseError = (webhookControllerRollSigningSecretResponse400 | webhookControllerRollSigningSecretResponse401 | webhookControllerRollSigningSecretResponse403 | webhookControllerRollSigningSecretResponse404) & {
  headers: Headers;
};

export type webhookControllerRollSigningSecretResponse = (webhookControllerRollSigningSecretResponseSuccess | webhookControllerRollSigningSecretResponseError)

export const getWebhookControllerRollSigningSecretUrl = (id: string,) => {




  return `/webhooks/${id}/secret/roll`
}

export const webhookControllerRollSigningSecret = async (id: string,
    rollSecretWebhookDto: RollSecretWebhookDto, options?: RequestInit): Promise<webhookControllerRollSigningSecretResponse> => {

  return customInstance<webhookControllerRollSigningSecretResponse>(getWebhookControllerRollSigningSecretUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rollSecretWebhookDto,)
  }
);}




export const getWebhookControllerRollSigningSecretMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerRollSigningSecret>>, TError,{id: string;data: RollSecretWebhookDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerRollSigningSecret>>, TError,{id: string;data: RollSecretWebhookDto}, TContext> => {

const mutationKey = ['webhookControllerRollSigningSecret'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerRollSigningSecret>>, {id: string;data: RollSecretWebhookDto}> = (props) => {
          const {id,data} = props ?? {};

          return  webhookControllerRollSigningSecret(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerRollSigningSecretMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerRollSigningSecret>>>
    export type WebhookControllerRollSigningSecretMutationBody = RollSecretWebhookDto
    export type WebhookControllerRollSigningSecretMutationError = ErrorType<BasicResponse>

    /**
 * @summary Roll Webhook Signing Secret
 */
export const useWebhookControllerRollSigningSecret = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerRollSigningSecret>>, TError,{id: string;data: RollSecretWebhookDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerRollSigningSecret>>,
        TError,
        {id: string;data: RollSecretWebhookDto},
        TContext
      > => {
      return useMutation(getWebhookControllerRollSigningSecretMutationOptions(options), queryClient);
    }
    /**
 * @summary Enable Webhook
 */
export type webhookControllerEnableResponse200 = {
  data: ResponseWrapperApiHydratedWebhook
  status: 200
}

export type webhookControllerEnableResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerEnableResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerEnableResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerEnableResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerEnableResponseSuccess = (webhookControllerEnableResponse200) & {
  headers: Headers;
};
export type webhookControllerEnableResponseError = (webhookControllerEnableResponse400 | webhookControllerEnableResponse401 | webhookControllerEnableResponse403 | webhookControllerEnableResponse404) & {
  headers: Headers;
};

export type webhookControllerEnableResponse = (webhookControllerEnableResponseSuccess | webhookControllerEnableResponseError)

export const getWebhookControllerEnableUrl = (id: string,) => {




  return `/webhooks/${id}/enable`
}

export const webhookControllerEnable = async (id: string, options?: RequestInit): Promise<webhookControllerEnableResponse> => {

  return customInstance<webhookControllerEnableResponse>(getWebhookControllerEnableUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getWebhookControllerEnableMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerEnable>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerEnable>>, TError,{id: string}, TContext> => {

const mutationKey = ['webhookControllerEnable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerEnable>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  webhookControllerEnable(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerEnableMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerEnable>>>

    export type WebhookControllerEnableMutationError = ErrorType<BasicResponse>

    /**
 * @summary Enable Webhook
 */
export const useWebhookControllerEnable = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerEnable>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerEnable>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getWebhookControllerEnableMutationOptions(options), queryClient);
    }
    /**
 * @summary Disable Webhook
 */
export type webhookControllerDisableResponse200 = {
  data: ResponseWrapperApiHydratedWebhook
  status: 200
}

export type webhookControllerDisableResponse400 = {
  data: BasicResponse
  status: 400
}

export type webhookControllerDisableResponse401 = {
  data: BasicResponse
  status: 401
}

export type webhookControllerDisableResponse403 = {
  data: BasicResponse
  status: 403
}

export type webhookControllerDisableResponse404 = {
  data: BasicResponse
  status: 404
}

export type webhookControllerDisableResponseSuccess = (webhookControllerDisableResponse200) & {
  headers: Headers;
};
export type webhookControllerDisableResponseError = (webhookControllerDisableResponse400 | webhookControllerDisableResponse401 | webhookControllerDisableResponse403 | webhookControllerDisableResponse404) & {
  headers: Headers;
};

export type webhookControllerDisableResponse = (webhookControllerDisableResponseSuccess | webhookControllerDisableResponseError)

export const getWebhookControllerDisableUrl = (id: string,) => {




  return `/webhooks/${id}/disable`
}

export const webhookControllerDisable = async (id: string, options?: RequestInit): Promise<webhookControllerDisableResponse> => {

  return customInstance<webhookControllerDisableResponse>(getWebhookControllerDisableUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getWebhookControllerDisableMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerDisable>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof webhookControllerDisable>>, TError,{id: string}, TContext> => {

const mutationKey = ['webhookControllerDisable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof webhookControllerDisable>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  webhookControllerDisable(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WebhookControllerDisableMutationResult = NonNullable<Awaited<ReturnType<typeof webhookControllerDisable>>>

    export type WebhookControllerDisableMutationError = ErrorType<BasicResponse>

    /**
 * @summary Disable Webhook
 */
export const useWebhookControllerDisable = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof webhookControllerDisable>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof webhookControllerDisable>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getWebhookControllerDisableMutationOptions(options), queryClient);
    }
