service:
  name: "{{ values:component.name }}"
  image: "{{ values:registry }}/{{ values:component.name }}:{{ values:app.tag }}"
  imagePull: always
  scale: {{ values:component.scale }}
  ports:
    - name: http
      port: {{ values:component.port }}
  expose:
    host: "{{ values:component.host }}"
    port: http
    tls:
      mode: manual
      secret: shared/cf-origin-cert
  env:
    NODE_ENV: production

  health:
    liveness:
      type: http
      path: "{{ values:component.healthPath }}"
      port: {{ values:component.port }}
      intervalSeconds: 10
      timeoutSeconds: 3
  resources:
    cpu:
      request: "50m"
      limit: "{{ values:component.cpuLimit }}"
    memory:
      request: "64Mi"
      limit: "{{ values:component.memLimit }}"
