service:
  name: landing
  image: "{{ values:registry }}/landing:{{ values:app.tag }}"
  imagePull: missing
  scale: {{ values:landing.scale }}
  ports:
    - name: http
      port: 80
  expose:
    host: "{{ values:landing.host }}"
    port: http
    tls:
      mode: auto
  env:
    NODE_ENV: production

  health:
    liveness:
      type: http
      path: /healthz
      port: 80
      intervalSeconds: 10
      timeoutSeconds: 3
  resources:
    cpu:
      request: "50m"
      limit: "{{ values:landing.cpuLimit }}"
    memory:
      request: "64Mi"
      limit: "{{ values:landing.memLimit }}"
