/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BasicResponse,
  CardBinControllerGetAccountLogsCSVParams,
  CardBinControllerGetAccountLogsParams,
  CardBinControllerGetAllParams,
  CardBinControllerGetParams,
  CreateCardBinDto,
  PatchCardBinDto,
  ResponseWrapperApiHydratedCardBin,
  ResponseWrapperApiHydratedCardBinAccountLogList,
  ResponseWrapperApiHydratedCardBinList
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Card Bins
 */
export type cardBinControllerGetAllResponse200 = {
  data: ResponseWrapperApiHydratedCardBinList
  status: 200
}

export type cardBinControllerGetAllResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerGetAllResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerGetAllResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerGetAllResponseSuccess = (cardBinControllerGetAllResponse200) & {
  headers: Headers;
};
export type cardBinControllerGetAllResponseError = (cardBinControllerGetAllResponse400 | cardBinControllerGetAllResponse401 | cardBinControllerGetAllResponse403) & {
  headers: Headers;
};

export type cardBinControllerGetAllResponse = (cardBinControllerGetAllResponseSuccess | cardBinControllerGetAllResponseError)

export const getCardBinControllerGetAllUrl = (params?: CardBinControllerGetAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/card-bins?${stringifiedParams}` : `/card-bins`
}

export const cardBinControllerGetAll = async (params?: CardBinControllerGetAllParams, options?: RequestInit): Promise<cardBinControllerGetAllResponse> => {

  return customInstance<cardBinControllerGetAllResponse>(getCardBinControllerGetAllUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCardBinControllerGetAllQueryKey = (params?: CardBinControllerGetAllParams,) => {
    return [
    `/card-bins`, ...(params ? [params] : [])
    ] as const;
    }


export const getCardBinControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError = ErrorType<BasicResponse>>(params?: CardBinControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardBinControllerGetAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardBinControllerGetAll>>> = ({ signal }) => cardBinControllerGetAll(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardBinControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerGetAll>>>
export type CardBinControllerGetAllQueryError = ErrorType<BasicResponse>


export function useCardBinControllerGetAll<TData = Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  CardBinControllerGetAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGetAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGetAll<TData = Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError = ErrorType<BasicResponse>>(
 params?: CardBinControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGetAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGetAll<TData = Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError = ErrorType<BasicResponse>>(
 params?: CardBinControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Card Bins
 */

export function useCardBinControllerGetAll<TData = Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError = ErrorType<BasicResponse>>(
 params?: CardBinControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardBinControllerGetAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Card Bin
 */
export type cardBinControllerCreateResponse201 = {
  data: ResponseWrapperApiHydratedCardBin
  status: 201
}

export type cardBinControllerCreateResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerCreateResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerCreateResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerCreateResponseSuccess = (cardBinControllerCreateResponse201) & {
  headers: Headers;
};
export type cardBinControllerCreateResponseError = (cardBinControllerCreateResponse400 | cardBinControllerCreateResponse401 | cardBinControllerCreateResponse403) & {
  headers: Headers;
};

export type cardBinControllerCreateResponse = (cardBinControllerCreateResponseSuccess | cardBinControllerCreateResponseError)

export const getCardBinControllerCreateUrl = () => {




  return `/card-bins`
}

export const cardBinControllerCreate = async (createCardBinDto: CreateCardBinDto, options?: RequestInit): Promise<cardBinControllerCreateResponse> => {

  return customInstance<cardBinControllerCreateResponse>(getCardBinControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCardBinDto,)
  }
);}




export const getCardBinControllerCreateMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerCreate>>, TError,{data: CreateCardBinDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerCreate>>, TError,{data: CreateCardBinDto}, TContext> => {

const mutationKey = ['cardBinControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardBinControllerCreate>>, {data: CreateCardBinDto}> = (props) => {
          const {data} = props ?? {};

          return  cardBinControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CardBinControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerCreate>>>
    export type CardBinControllerCreateMutationBody = CreateCardBinDto
    export type CardBinControllerCreateMutationError = ErrorType<BasicResponse>

    /**
 * @summary Create Card Bin
 */
export const useCardBinControllerCreate = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerCreate>>, TError,{data: CreateCardBinDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardBinControllerCreate>>,
        TError,
        {data: CreateCardBinDto},
        TContext
      > => {
      return useMutation(getCardBinControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Card Bin
 */
export type cardBinControllerGetResponse200 = {
  data: ResponseWrapperApiHydratedCardBin
  status: 200
}

export type cardBinControllerGetResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerGetResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerGetResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerGetResponse404 = {
  data: BasicResponse
  status: 404
}

export type cardBinControllerGetResponseSuccess = (cardBinControllerGetResponse200) & {
  headers: Headers;
};
export type cardBinControllerGetResponseError = (cardBinControllerGetResponse400 | cardBinControllerGetResponse401 | cardBinControllerGetResponse403 | cardBinControllerGetResponse404) & {
  headers: Headers;
};

export type cardBinControllerGetResponse = (cardBinControllerGetResponseSuccess | cardBinControllerGetResponseError)

export const getCardBinControllerGetUrl = (id: string,
    params?: CardBinControllerGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/card-bins/${id}?${stringifiedParams}` : `/card-bins/${id}`
}

export const cardBinControllerGet = async (id: string,
    params?: CardBinControllerGetParams, options?: RequestInit): Promise<cardBinControllerGetResponse> => {

  return customInstance<cardBinControllerGetResponse>(getCardBinControllerGetUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCardBinControllerGetQueryKey = (id: string,
    params?: CardBinControllerGetParams,) => {
    return [
    `/card-bins/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getCardBinControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof cardBinControllerGet>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: CardBinControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardBinControllerGetQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardBinControllerGet>>> = ({ signal }) => cardBinControllerGet(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardBinControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerGet>>>
export type CardBinControllerGetQueryError = ErrorType<BasicResponse>


export function useCardBinControllerGet<TData = Awaited<ReturnType<typeof cardBinControllerGet>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  CardBinControllerGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGet>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGet<TData = Awaited<ReturnType<typeof cardBinControllerGet>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGet>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGet<TData = Awaited<ReturnType<typeof cardBinControllerGet>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Card Bin
 */

export function useCardBinControllerGet<TData = Awaited<ReturnType<typeof cardBinControllerGet>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardBinControllerGetQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Card Bin
 */
export type cardBinControllerPatchResponse200 = {
  data: ResponseWrapperApiHydratedCardBin
  status: 200
}

export type cardBinControllerPatchResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerPatchResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerPatchResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerPatchResponse404 = {
  data: BasicResponse
  status: 404
}

export type cardBinControllerPatchResponseSuccess = (cardBinControllerPatchResponse200) & {
  headers: Headers;
};
export type cardBinControllerPatchResponseError = (cardBinControllerPatchResponse400 | cardBinControllerPatchResponse401 | cardBinControllerPatchResponse403 | cardBinControllerPatchResponse404) & {
  headers: Headers;
};

export type cardBinControllerPatchResponse = (cardBinControllerPatchResponseSuccess | cardBinControllerPatchResponseError)

export const getCardBinControllerPatchUrl = (id: string,) => {




  return `/card-bins/${id}`
}

export const cardBinControllerPatch = async (id: string,
    patchCardBinDto: PatchCardBinDto, options?: RequestInit): Promise<cardBinControllerPatchResponse> => {

  return customInstance<cardBinControllerPatchResponse>(getCardBinControllerPatchUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchCardBinDto,)
  }
);}




export const getCardBinControllerPatchMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerPatch>>, TError,{id: string;data: PatchCardBinDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerPatch>>, TError,{id: string;data: PatchCardBinDto}, TContext> => {

const mutationKey = ['cardBinControllerPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardBinControllerPatch>>, {id: string;data: PatchCardBinDto}> = (props) => {
          const {id,data} = props ?? {};

          return  cardBinControllerPatch(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CardBinControllerPatchMutationResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerPatch>>>
    export type CardBinControllerPatchMutationBody = PatchCardBinDto
    export type CardBinControllerPatchMutationError = ErrorType<BasicResponse>

    /**
 * @summary Update Card Bin
 */
export const useCardBinControllerPatch = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerPatch>>, TError,{id: string;data: PatchCardBinDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardBinControllerPatch>>,
        TError,
        {id: string;data: PatchCardBinDto},
        TContext
      > => {
      return useMutation(getCardBinControllerPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Request Card Bin Approval
 */
export type cardBinControllerRequestApprovalResponse200 = {
  data: ResponseWrapperApiHydratedCardBin
  status: 200
}

export type cardBinControllerRequestApprovalResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerRequestApprovalResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerRequestApprovalResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerRequestApprovalResponse404 = {
  data: BasicResponse
  status: 404
}

export type cardBinControllerRequestApprovalResponseSuccess = (cardBinControllerRequestApprovalResponse200) & {
  headers: Headers;
};
export type cardBinControllerRequestApprovalResponseError = (cardBinControllerRequestApprovalResponse400 | cardBinControllerRequestApprovalResponse401 | cardBinControllerRequestApprovalResponse403 | cardBinControllerRequestApprovalResponse404) & {
  headers: Headers;
};

export type cardBinControllerRequestApprovalResponse = (cardBinControllerRequestApprovalResponseSuccess | cardBinControllerRequestApprovalResponseError)

export const getCardBinControllerRequestApprovalUrl = (id: string,) => {




  return `/card-bins/${id}/request-approval`
}

export const cardBinControllerRequestApproval = async (id: string, options?: RequestInit): Promise<cardBinControllerRequestApprovalResponse> => {

  return customInstance<cardBinControllerRequestApprovalResponse>(getCardBinControllerRequestApprovalUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getCardBinControllerRequestApprovalMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerRequestApproval>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerRequestApproval>>, TError,{id: string}, TContext> => {

const mutationKey = ['cardBinControllerRequestApproval'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cardBinControllerRequestApproval>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  cardBinControllerRequestApproval(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CardBinControllerRequestApprovalMutationResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerRequestApproval>>>

    export type CardBinControllerRequestApprovalMutationError = ErrorType<BasicResponse>

    /**
 * @summary Request Card Bin Approval
 */
export const useCardBinControllerRequestApproval = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cardBinControllerRequestApproval>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cardBinControllerRequestApproval>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getCardBinControllerRequestApprovalMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Card Bin Account Logs
 */
export type cardBinControllerGetAccountLogsResponse200 = {
  data: ResponseWrapperApiHydratedCardBinAccountLogList
  status: 200
}

export type cardBinControllerGetAccountLogsResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerGetAccountLogsResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerGetAccountLogsResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerGetAccountLogsResponse404 = {
  data: BasicResponse
  status: 404
}

export type cardBinControllerGetAccountLogsResponseSuccess = (cardBinControllerGetAccountLogsResponse200) & {
  headers: Headers;
};
export type cardBinControllerGetAccountLogsResponseError = (cardBinControllerGetAccountLogsResponse400 | cardBinControllerGetAccountLogsResponse401 | cardBinControllerGetAccountLogsResponse403 | cardBinControllerGetAccountLogsResponse404) & {
  headers: Headers;
};

export type cardBinControllerGetAccountLogsResponse = (cardBinControllerGetAccountLogsResponseSuccess | cardBinControllerGetAccountLogsResponseError)

export const getCardBinControllerGetAccountLogsUrl = (id: string,
    params?: CardBinControllerGetAccountLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/card-bins/${id}/account-logs?${stringifiedParams}` : `/card-bins/${id}/account-logs`
}

export const cardBinControllerGetAccountLogs = async (id: string,
    params?: CardBinControllerGetAccountLogsParams, options?: RequestInit): Promise<cardBinControllerGetAccountLogsResponse> => {

  return customInstance<cardBinControllerGetAccountLogsResponse>(getCardBinControllerGetAccountLogsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCardBinControllerGetAccountLogsQueryKey = (id: string,
    params?: CardBinControllerGetAccountLogsParams,) => {
    return [
    `/card-bins/${id}/account-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getCardBinControllerGetAccountLogsQueryOptions = <TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: CardBinControllerGetAccountLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardBinControllerGetAccountLogsQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>> = ({ signal }) => cardBinControllerGetAccountLogs(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardBinControllerGetAccountLogsQueryResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>>
export type CardBinControllerGetAccountLogsQueryError = ErrorType<BasicResponse>


export function useCardBinControllerGetAccountLogs<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  CardBinControllerGetAccountLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGetAccountLogs<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetAccountLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGetAccountLogs<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetAccountLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Card Bin Account Logs
 */

export function useCardBinControllerGetAccountLogs<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetAccountLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardBinControllerGetAccountLogsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download Card Bin Account Logs CSV
 */
export type cardBinControllerGetAccountLogsCSVResponse200 = {
  data: BasicResponse
  status: 200
}

export type cardBinControllerGetAccountLogsCSVResponse400 = {
  data: BasicResponse
  status: 400
}

export type cardBinControllerGetAccountLogsCSVResponse401 = {
  data: BasicResponse
  status: 401
}

export type cardBinControllerGetAccountLogsCSVResponse403 = {
  data: BasicResponse
  status: 403
}

export type cardBinControllerGetAccountLogsCSVResponse404 = {
  data: BasicResponse
  status: 404
}

export type cardBinControllerGetAccountLogsCSVResponseSuccess = (cardBinControllerGetAccountLogsCSVResponse200) & {
  headers: Headers;
};
export type cardBinControllerGetAccountLogsCSVResponseError = (cardBinControllerGetAccountLogsCSVResponse400 | cardBinControllerGetAccountLogsCSVResponse401 | cardBinControllerGetAccountLogsCSVResponse403 | cardBinControllerGetAccountLogsCSVResponse404) & {
  headers: Headers;
};

export type cardBinControllerGetAccountLogsCSVResponse = (cardBinControllerGetAccountLogsCSVResponseSuccess | cardBinControllerGetAccountLogsCSVResponseError)

export const getCardBinControllerGetAccountLogsCSVUrl = (id: string,
    params?: CardBinControllerGetAccountLogsCSVParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/card-bins/${id}/account-logs/csv?${stringifiedParams}` : `/card-bins/${id}/account-logs/csv`
}

export const cardBinControllerGetAccountLogsCSV = async (id: string,
    params?: CardBinControllerGetAccountLogsCSVParams, options?: RequestInit): Promise<cardBinControllerGetAccountLogsCSVResponse> => {

  return customInstance<cardBinControllerGetAccountLogsCSVResponse>(getCardBinControllerGetAccountLogsCSVUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCardBinControllerGetAccountLogsCSVQueryKey = (id: string,
    params?: CardBinControllerGetAccountLogsCSVParams,) => {
    return [
    `/card-bins/${id}/account-logs/csv`, ...(params ? [params] : [])
    ] as const;
    }


export const getCardBinControllerGetAccountLogsCSVQueryOptions = <TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: CardBinControllerGetAccountLogsCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCardBinControllerGetAccountLogsCSVQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>> = ({ signal }) => cardBinControllerGetAccountLogsCSV(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CardBinControllerGetAccountLogsCSVQueryResult = NonNullable<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>>
export type CardBinControllerGetAccountLogsCSVQueryError = ErrorType<BasicResponse>


export function useCardBinControllerGetAccountLogsCSV<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  CardBinControllerGetAccountLogsCSVParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGetAccountLogsCSV<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetAccountLogsCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>,
          TError,
          Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCardBinControllerGetAccountLogsCSV<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetAccountLogsCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Card Bin Account Logs CSV
 */

export function useCardBinControllerGetAccountLogsCSV<TData = Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: CardBinControllerGetAccountLogsCSVParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cardBinControllerGetAccountLogsCSV>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCardBinControllerGetAccountLogsCSVQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




