/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BasicResponse,
  BusinessControllerFindParams,
  BusinessControllerGetBusinessParams,
  InviteUserDto,
  ResponseWrapperApiHydratedBusiness,
  ResponseWrapperApiHydratedBusinessList
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Business
 */
export type businessControllerFindResponse200 = {
  data: ResponseWrapperApiHydratedBusiness
  status: 200
}

export type businessControllerFindResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessControllerFindResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessControllerFindResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessControllerFindResponseSuccess = (businessControllerFindResponse200) & {
  headers: Headers;
};
export type businessControllerFindResponseError = (businessControllerFindResponse400 | businessControllerFindResponse401 | businessControllerFindResponse403) & {
  headers: Headers;
};

export type businessControllerFindResponse = (businessControllerFindResponseSuccess | businessControllerFindResponseError)

export const getBusinessControllerFindUrl = (params?: BusinessControllerFindParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/business?${stringifiedParams}` : `/business`
}

export const businessControllerFind = async (params?: BusinessControllerFindParams, options?: RequestInit): Promise<businessControllerFindResponse> => {

  return customInstance<businessControllerFindResponse>(getBusinessControllerFindUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBusinessControllerFindQueryKey = (params?: BusinessControllerFindParams,) => {
    return [
    `/business`, ...(params ? [params] : [])
    ] as const;
    }


export const getBusinessControllerFindQueryOptions = <TData = Awaited<ReturnType<typeof businessControllerFind>>, TError = ErrorType<BasicResponse>>(params?: BusinessControllerFindParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerFind>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBusinessControllerFindQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof businessControllerFind>>> = ({ signal }) => businessControllerFind(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof businessControllerFind>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BusinessControllerFindQueryResult = NonNullable<Awaited<ReturnType<typeof businessControllerFind>>>
export type BusinessControllerFindQueryError = ErrorType<BasicResponse>


export function useBusinessControllerFind<TData = Awaited<ReturnType<typeof businessControllerFind>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  BusinessControllerFindParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerFind>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessControllerFind>>,
          TError,
          Awaited<ReturnType<typeof businessControllerFind>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessControllerFind<TData = Awaited<ReturnType<typeof businessControllerFind>>, TError = ErrorType<BasicResponse>>(
 params?: BusinessControllerFindParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerFind>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessControllerFind>>,
          TError,
          Awaited<ReturnType<typeof businessControllerFind>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessControllerFind<TData = Awaited<ReturnType<typeof businessControllerFind>>, TError = ErrorType<BasicResponse>>(
 params?: BusinessControllerFindParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerFind>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Business
 */

export function useBusinessControllerFind<TData = Awaited<ReturnType<typeof businessControllerFind>>, TError = ErrorType<BasicResponse>>(
 params?: BusinessControllerFindParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerFind>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBusinessControllerFindQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Business Info
 */
export type businessControllerGetInfoResponse200 = {
  data: ResponseWrapperApiHydratedBusiness
  status: 200
}

export type businessControllerGetInfoResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessControllerGetInfoResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessControllerGetInfoResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessControllerGetInfoResponseSuccess = (businessControllerGetInfoResponse200) & {
  headers: Headers;
};
export type businessControllerGetInfoResponseError = (businessControllerGetInfoResponse400 | businessControllerGetInfoResponse401 | businessControllerGetInfoResponse403) & {
  headers: Headers;
};

export type businessControllerGetInfoResponse = (businessControllerGetInfoResponseSuccess | businessControllerGetInfoResponseError)

export const getBusinessControllerGetInfoUrl = () => {




  return `/business/info`
}

export const businessControllerGetInfo = async ( options?: RequestInit): Promise<businessControllerGetInfoResponse> => {

  return customInstance<businessControllerGetInfoResponse>(getBusinessControllerGetInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBusinessControllerGetInfoQueryKey = () => {
    return [
    `/business/info`
    ] as const;
    }


export const getBusinessControllerGetInfoQueryOptions = <TData = Awaited<ReturnType<typeof businessControllerGetInfo>>, TError = ErrorType<BasicResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBusinessControllerGetInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof businessControllerGetInfo>>> = ({ signal }) => businessControllerGetInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BusinessControllerGetInfoQueryResult = NonNullable<Awaited<ReturnType<typeof businessControllerGetInfo>>>
export type BusinessControllerGetInfoQueryError = ErrorType<BasicResponse>


export function useBusinessControllerGetInfo<TData = Awaited<ReturnType<typeof businessControllerGetInfo>>, TError = ErrorType<BasicResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessControllerGetInfo>>,
          TError,
          Awaited<ReturnType<typeof businessControllerGetInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessControllerGetInfo<TData = Awaited<ReturnType<typeof businessControllerGetInfo>>, TError = ErrorType<BasicResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessControllerGetInfo>>,
          TError,
          Awaited<ReturnType<typeof businessControllerGetInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessControllerGetInfo<TData = Awaited<ReturnType<typeof businessControllerGetInfo>>, TError = ErrorType<BasicResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Business Info
 */

export function useBusinessControllerGetInfo<TData = Awaited<ReturnType<typeof businessControllerGetInfo>>, TError = ErrorType<BasicResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBusinessControllerGetInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Invite User
 */
export type businessControllerCreateResponse200 = {
  data: BasicResponse
  status: 200
}

export type businessControllerCreateResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessControllerCreateResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessControllerCreateResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessControllerCreateResponseSuccess = (businessControllerCreateResponse200) & {
  headers: Headers;
};
export type businessControllerCreateResponseError = (businessControllerCreateResponse400 | businessControllerCreateResponse401 | businessControllerCreateResponse403) & {
  headers: Headers;
};

export type businessControllerCreateResponse = (businessControllerCreateResponseSuccess | businessControllerCreateResponseError)

export const getBusinessControllerCreateUrl = () => {




  return `/business/invite`
}

export const businessControllerCreate = async (inviteUserDto: InviteUserDto, options?: RequestInit): Promise<businessControllerCreateResponse> => {

  return customInstance<businessControllerCreateResponse>(getBusinessControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      inviteUserDto,)
  }
);}




export const getBusinessControllerCreateMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessControllerCreate>>, TError,{data: InviteUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessControllerCreate>>, TError,{data: InviteUserDto}, TContext> => {

const mutationKey = ['businessControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessControllerCreate>>, {data: InviteUserDto}> = (props) => {
          const {data} = props ?? {};

          return  businessControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof businessControllerCreate>>>
    export type BusinessControllerCreateMutationBody = InviteUserDto
    export type BusinessControllerCreateMutationError = ErrorType<BasicResponse>

    /**
 * @summary Invite User
 */
export const useBusinessControllerCreate = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessControllerCreate>>, TError,{data: InviteUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessControllerCreate>>,
        TError,
        {data: InviteUserDto},
        TContext
      > => {
      return useMutation(getBusinessControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Revoke User Invite
 */
export type businessControllerRevokeInviteResponse200 = {
  data: BasicResponse
  status: 200
}

export type businessControllerRevokeInviteResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessControllerRevokeInviteResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessControllerRevokeInviteResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessControllerRevokeInviteResponse404 = {
  data: BasicResponse
  status: 404
}

export type businessControllerRevokeInviteResponseSuccess = (businessControllerRevokeInviteResponse200) & {
  headers: Headers;
};
export type businessControllerRevokeInviteResponseError = (businessControllerRevokeInviteResponse400 | businessControllerRevokeInviteResponse401 | businessControllerRevokeInviteResponse403 | businessControllerRevokeInviteResponse404) & {
  headers: Headers;
};

export type businessControllerRevokeInviteResponse = (businessControllerRevokeInviteResponseSuccess | businessControllerRevokeInviteResponseError)

export const getBusinessControllerRevokeInviteUrl = (id: string,) => {




  return `/business/invite/${id}`
}

export const businessControllerRevokeInvite = async (id: string, options?: RequestInit): Promise<businessControllerRevokeInviteResponse> => {

  return customInstance<businessControllerRevokeInviteResponse>(getBusinessControllerRevokeInviteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getBusinessControllerRevokeInviteMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessControllerRevokeInvite>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof businessControllerRevokeInvite>>, TError,{id: string}, TContext> => {

const mutationKey = ['businessControllerRevokeInvite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof businessControllerRevokeInvite>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  businessControllerRevokeInvite(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BusinessControllerRevokeInviteMutationResult = NonNullable<Awaited<ReturnType<typeof businessControllerRevokeInvite>>>

    export type BusinessControllerRevokeInviteMutationError = ErrorType<BasicResponse>

    /**
 * @summary Revoke User Invite
 */
export const useBusinessControllerRevokeInvite = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof businessControllerRevokeInvite>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof businessControllerRevokeInvite>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getBusinessControllerRevokeInviteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Business Members
 */
export type businessControllerGetBusinessResponse200 = {
  data: ResponseWrapperApiHydratedBusinessList
  status: 200
}

export type businessControllerGetBusinessResponse400 = {
  data: BasicResponse
  status: 400
}

export type businessControllerGetBusinessResponse401 = {
  data: BasicResponse
  status: 401
}

export type businessControllerGetBusinessResponse403 = {
  data: BasicResponse
  status: 403
}

export type businessControllerGetBusinessResponseSuccess = (businessControllerGetBusinessResponse200) & {
  headers: Headers;
};
export type businessControllerGetBusinessResponseError = (businessControllerGetBusinessResponse400 | businessControllerGetBusinessResponse401 | businessControllerGetBusinessResponse403) & {
  headers: Headers;
};

export type businessControllerGetBusinessResponse = (businessControllerGetBusinessResponseSuccess | businessControllerGetBusinessResponseError)

export const getBusinessControllerGetBusinessUrl = (params?: BusinessControllerGetBusinessParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/business/members?${stringifiedParams}` : `/business/members`
}

export const businessControllerGetBusiness = async (params?: BusinessControllerGetBusinessParams, options?: RequestInit): Promise<businessControllerGetBusinessResponse> => {

  return customInstance<businessControllerGetBusinessResponse>(getBusinessControllerGetBusinessUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBusinessControllerGetBusinessQueryKey = (params?: BusinessControllerGetBusinessParams,) => {
    return [
    `/business/members`, ...(params ? [params] : [])
    ] as const;
    }


export const getBusinessControllerGetBusinessQueryOptions = <TData = Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError = ErrorType<BasicResponse>>(params?: BusinessControllerGetBusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBusinessControllerGetBusinessQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof businessControllerGetBusiness>>> = ({ signal }) => businessControllerGetBusiness(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BusinessControllerGetBusinessQueryResult = NonNullable<Awaited<ReturnType<typeof businessControllerGetBusiness>>>
export type BusinessControllerGetBusinessQueryError = ErrorType<BasicResponse>


export function useBusinessControllerGetBusiness<TData = Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  BusinessControllerGetBusinessParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessControllerGetBusiness>>,
          TError,
          Awaited<ReturnType<typeof businessControllerGetBusiness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessControllerGetBusiness<TData = Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError = ErrorType<BasicResponse>>(
 params?: BusinessControllerGetBusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessControllerGetBusiness>>,
          TError,
          Awaited<ReturnType<typeof businessControllerGetBusiness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBusinessControllerGetBusiness<TData = Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError = ErrorType<BasicResponse>>(
 params?: BusinessControllerGetBusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Business Members
 */

export function useBusinessControllerGetBusiness<TData = Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError = ErrorType<BasicResponse>>(
 params?: BusinessControllerGetBusinessParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof businessControllerGetBusiness>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBusinessControllerGetBusinessQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




