/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BasicResponse,
  FxBuyQuoteDto,
  FxQuoteDto,
  FxSellQuoteDto,
  ResponseWrapperBankList,
  ResponseWrapperFxQuote,
  ResponseWrapperFxRate,
  ResponseWrapperMerchant,
  ResponseWrapperMerchantList,
  ResponseWrapperResolvedAccount,
  ResponseWrapperTempFileUploadResult,
  ToolsControllerGetFxRateParams,
  ToolsControllerGetMerchantsParams,
  ToolsControllerGetOneMerchantParams,
  ToolsControllerResolveBankAccountParams
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Bank list
 */
export type toolsControllerGetBanksResponse200 = {
  data: ResponseWrapperBankList
  status: 200
}

export type toolsControllerGetBanksResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetBanksResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetBanksResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetBanksResponseSuccess = (toolsControllerGetBanksResponse200) & {
  headers: Headers;
};
export type toolsControllerGetBanksResponseError = (toolsControllerGetBanksResponse400 | toolsControllerGetBanksResponse401 | toolsControllerGetBanksResponse403) & {
  headers: Headers;
};

export type toolsControllerGetBanksResponse = (toolsControllerGetBanksResponseSuccess | toolsControllerGetBanksResponseError)

export const getToolsControllerGetBanksUrl = () => {




  return `/tools/banks`
}

export const toolsControllerGetBanks = async ( options?: RequestInit): Promise<toolsControllerGetBanksResponse> => {

  return customInstance<toolsControllerGetBanksResponse>(getToolsControllerGetBanksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getToolsControllerGetBanksQueryKey = () => {
    return [
    `/tools/banks`
    ] as const;
    }


export const getToolsControllerGetBanksQueryOptions = <TData = Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError = ErrorType<BasicResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsControllerGetBanksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof toolsControllerGetBanks>>> = ({ signal }) => toolsControllerGetBanks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsControllerGetBanksQueryResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetBanks>>>
export type ToolsControllerGetBanksQueryError = ErrorType<BasicResponse>


export function useToolsControllerGetBanks<TData = Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError = ErrorType<BasicResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetBanks>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetBanks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetBanks<TData = Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError = ErrorType<BasicResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetBanks>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetBanks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetBanks<TData = Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError = ErrorType<BasicResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Bank list
 */

export function useToolsControllerGetBanks<TData = Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError = ErrorType<BasicResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetBanks>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsControllerGetBanksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Bank Short List
 */
export type toolsControllerGetShortBankListResponse200 = {
  data: ResponseWrapperBankList
  status: 200
}

export type toolsControllerGetShortBankListResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetShortBankListResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetShortBankListResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetShortBankListResponseSuccess = (toolsControllerGetShortBankListResponse200) & {
  headers: Headers;
};
export type toolsControllerGetShortBankListResponseError = (toolsControllerGetShortBankListResponse400 | toolsControllerGetShortBankListResponse401 | toolsControllerGetShortBankListResponse403) & {
  headers: Headers;
};

export type toolsControllerGetShortBankListResponse = (toolsControllerGetShortBankListResponseSuccess | toolsControllerGetShortBankListResponseError)

export const getToolsControllerGetShortBankListUrl = (id: string,) => {




  return `/tools/banks/short-list/${id}`
}

export const toolsControllerGetShortBankList = async (id: string, options?: RequestInit): Promise<toolsControllerGetShortBankListResponse> => {

  return customInstance<toolsControllerGetShortBankListResponse>(getToolsControllerGetShortBankListUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getToolsControllerGetShortBankListQueryKey = (id: string,) => {
    return [
    `/tools/banks/short-list/${id}`
    ] as const;
    }


export const getToolsControllerGetShortBankListQueryOptions = <TData = Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError = ErrorType<BasicResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsControllerGetShortBankListQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>> = ({ signal }) => toolsControllerGetShortBankList(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsControllerGetShortBankListQueryResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>>
export type ToolsControllerGetShortBankListQueryError = ErrorType<BasicResponse>


export function useToolsControllerGetShortBankList<TData = Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError = ErrorType<BasicResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetShortBankList>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetShortBankList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetShortBankList<TData = Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetShortBankList>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetShortBankList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetShortBankList<TData = Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Bank Short List
 */

export function useToolsControllerGetShortBankList<TData = Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError = ErrorType<BasicResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetShortBankList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsControllerGetShortBankListQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Resolve Bank Account
 */
export type toolsControllerResolveBankAccountResponse200 = {
  data: ResponseWrapperResolvedAccount
  status: 200
}

export type toolsControllerResolveBankAccountResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerResolveBankAccountResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerResolveBankAccountResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerResolveBankAccountResponseSuccess = (toolsControllerResolveBankAccountResponse200) & {
  headers: Headers;
};
export type toolsControllerResolveBankAccountResponseError = (toolsControllerResolveBankAccountResponse400 | toolsControllerResolveBankAccountResponse401 | toolsControllerResolveBankAccountResponse403) & {
  headers: Headers;
};

export type toolsControllerResolveBankAccountResponse = (toolsControllerResolveBankAccountResponseSuccess | toolsControllerResolveBankAccountResponseError)

export const getToolsControllerResolveBankAccountUrl = (params: ToolsControllerResolveBankAccountParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tools/banks/resolve?${stringifiedParams}` : `/tools/banks/resolve`
}

export const toolsControllerResolveBankAccount = async (params: ToolsControllerResolveBankAccountParams, options?: RequestInit): Promise<toolsControllerResolveBankAccountResponse> => {

  return customInstance<toolsControllerResolveBankAccountResponse>(getToolsControllerResolveBankAccountUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getToolsControllerResolveBankAccountQueryKey = (params?: ToolsControllerResolveBankAccountParams,) => {
    return [
    `/tools/banks/resolve`, ...(params ? [params] : [])
    ] as const;
    }


export const getToolsControllerResolveBankAccountQueryOptions = <TData = Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError = ErrorType<BasicResponse>>(params: ToolsControllerResolveBankAccountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsControllerResolveBankAccountQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>> = ({ signal }) => toolsControllerResolveBankAccount(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsControllerResolveBankAccountQueryResult = NonNullable<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>>
export type ToolsControllerResolveBankAccountQueryError = ErrorType<BasicResponse>


export function useToolsControllerResolveBankAccount<TData = Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError = ErrorType<BasicResponse>>(
 params: ToolsControllerResolveBankAccountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerResolveBankAccount<TData = Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError = ErrorType<BasicResponse>>(
 params: ToolsControllerResolveBankAccountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerResolveBankAccount<TData = Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError = ErrorType<BasicResponse>>(
 params: ToolsControllerResolveBankAccountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Resolve Bank Account
 */

export function useToolsControllerResolveBankAccount<TData = Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError = ErrorType<BasicResponse>>(
 params: ToolsControllerResolveBankAccountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerResolveBankAccount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsControllerResolveBankAccountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Merchants
 */
export type toolsControllerGetMerchantsResponse200 = {
  data: ResponseWrapperMerchantList
  status: 200
}

export type toolsControllerGetMerchantsResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetMerchantsResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetMerchantsResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetMerchantsResponseSuccess = (toolsControllerGetMerchantsResponse200) & {
  headers: Headers;
};
export type toolsControllerGetMerchantsResponseError = (toolsControllerGetMerchantsResponse400 | toolsControllerGetMerchantsResponse401 | toolsControllerGetMerchantsResponse403) & {
  headers: Headers;
};

export type toolsControllerGetMerchantsResponse = (toolsControllerGetMerchantsResponseSuccess | toolsControllerGetMerchantsResponseError)

export const getToolsControllerGetMerchantsUrl = (params?: ToolsControllerGetMerchantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tools/merchants?${stringifiedParams}` : `/tools/merchants`
}

export const toolsControllerGetMerchants = async (params?: ToolsControllerGetMerchantsParams, options?: RequestInit): Promise<toolsControllerGetMerchantsResponse> => {

  return customInstance<toolsControllerGetMerchantsResponse>(getToolsControllerGetMerchantsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getToolsControllerGetMerchantsQueryKey = (params?: ToolsControllerGetMerchantsParams,) => {
    return [
    `/tools/merchants`, ...(params ? [params] : [])
    ] as const;
    }


export const getToolsControllerGetMerchantsQueryOptions = <TData = Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError = ErrorType<BasicResponse>>(params?: ToolsControllerGetMerchantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsControllerGetMerchantsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof toolsControllerGetMerchants>>> = ({ signal }) => toolsControllerGetMerchants(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsControllerGetMerchantsQueryResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetMerchants>>>
export type ToolsControllerGetMerchantsQueryError = ErrorType<BasicResponse>


export function useToolsControllerGetMerchants<TData = Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  ToolsControllerGetMerchantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetMerchants>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetMerchants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetMerchants<TData = Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError = ErrorType<BasicResponse>>(
 params?: ToolsControllerGetMerchantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetMerchants>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetMerchants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetMerchants<TData = Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError = ErrorType<BasicResponse>>(
 params?: ToolsControllerGetMerchantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Merchants
 */

export function useToolsControllerGetMerchants<TData = Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError = ErrorType<BasicResponse>>(
 params?: ToolsControllerGetMerchantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetMerchants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsControllerGetMerchantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get One Merchant
 */
export type toolsControllerGetOneMerchantResponse200 = {
  data: ResponseWrapperMerchant
  status: 200
}

export type toolsControllerGetOneMerchantResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetOneMerchantResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetOneMerchantResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetOneMerchantResponse404 = {
  data: BasicResponse
  status: 404
}

export type toolsControllerGetOneMerchantResponseSuccess = (toolsControllerGetOneMerchantResponse200) & {
  headers: Headers;
};
export type toolsControllerGetOneMerchantResponseError = (toolsControllerGetOneMerchantResponse400 | toolsControllerGetOneMerchantResponse401 | toolsControllerGetOneMerchantResponse403 | toolsControllerGetOneMerchantResponse404) & {
  headers: Headers;
};

export type toolsControllerGetOneMerchantResponse = (toolsControllerGetOneMerchantResponseSuccess | toolsControllerGetOneMerchantResponseError)

export const getToolsControllerGetOneMerchantUrl = (id: string,
    params?: ToolsControllerGetOneMerchantParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tools/merchants/${id}?${stringifiedParams}` : `/tools/merchants/${id}`
}

export const toolsControllerGetOneMerchant = async (id: string,
    params?: ToolsControllerGetOneMerchantParams, options?: RequestInit): Promise<toolsControllerGetOneMerchantResponse> => {

  return customInstance<toolsControllerGetOneMerchantResponse>(getToolsControllerGetOneMerchantUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getToolsControllerGetOneMerchantQueryKey = (id: string,
    params?: ToolsControllerGetOneMerchantParams,) => {
    return [
    `/tools/merchants/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getToolsControllerGetOneMerchantQueryOptions = <TData = Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: ToolsControllerGetOneMerchantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsControllerGetOneMerchantQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>> = ({ signal }) => toolsControllerGetOneMerchant(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsControllerGetOneMerchantQueryResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>>
export type ToolsControllerGetOneMerchantQueryError = ErrorType<BasicResponse>


export function useToolsControllerGetOneMerchant<TData = Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  ToolsControllerGetOneMerchantParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetOneMerchant<TData = Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: ToolsControllerGetOneMerchantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetOneMerchant<TData = Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: ToolsControllerGetOneMerchantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get One Merchant
 */

export function useToolsControllerGetOneMerchant<TData = Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: ToolsControllerGetOneMerchantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetOneMerchant>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsControllerGetOneMerchantQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Current FX Rate
 */
export type toolsControllerGetFxRateResponse200 = {
  data: ResponseWrapperFxRate
  status: 200
}

export type toolsControllerGetFxRateResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetFxRateResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetFxRateResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetFxRateResponseSuccess = (toolsControllerGetFxRateResponse200) & {
  headers: Headers;
};
export type toolsControllerGetFxRateResponseError = (toolsControllerGetFxRateResponse400 | toolsControllerGetFxRateResponse401 | toolsControllerGetFxRateResponse403) & {
  headers: Headers;
};

export type toolsControllerGetFxRateResponse = (toolsControllerGetFxRateResponseSuccess | toolsControllerGetFxRateResponseError)

export const getToolsControllerGetFxRateUrl = (params?: ToolsControllerGetFxRateParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tools/fx/rate?${stringifiedParams}` : `/tools/fx/rate`
}

export const toolsControllerGetFxRate = async (params?: ToolsControllerGetFxRateParams, options?: RequestInit): Promise<toolsControllerGetFxRateResponse> => {

  return customInstance<toolsControllerGetFxRateResponse>(getToolsControllerGetFxRateUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getToolsControllerGetFxRateQueryKey = (params?: ToolsControllerGetFxRateParams,) => {
    return [
    `/tools/fx/rate`, ...(params ? [params] : [])
    ] as const;
    }


export const getToolsControllerGetFxRateQueryOptions = <TData = Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError = ErrorType<BasicResponse>>(params?: ToolsControllerGetFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsControllerGetFxRateQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof toolsControllerGetFxRate>>> = ({ signal }) => toolsControllerGetFxRate(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsControllerGetFxRateQueryResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetFxRate>>>
export type ToolsControllerGetFxRateQueryError = ErrorType<BasicResponse>


export function useToolsControllerGetFxRate<TData = Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  ToolsControllerGetFxRateParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetFxRate>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetFxRate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetFxRate<TData = Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError = ErrorType<BasicResponse>>(
 params?: ToolsControllerGetFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof toolsControllerGetFxRate>>,
          TError,
          Awaited<ReturnType<typeof toolsControllerGetFxRate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useToolsControllerGetFxRate<TData = Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError = ErrorType<BasicResponse>>(
 params?: ToolsControllerGetFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current FX Rate
 */

export function useToolsControllerGetFxRate<TData = Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError = ErrorType<BasicResponse>>(
 params?: ToolsControllerGetFxRateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof toolsControllerGetFxRate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsControllerGetFxRateQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get FX Quote
 */
export type toolsControllerGetFxQuoteResponse200 = {
  data: ResponseWrapperFxQuote
  status: 200
}

export type toolsControllerGetFxQuoteResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetFxQuoteResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetFxQuoteResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetFxQuoteResponseSuccess = (toolsControllerGetFxQuoteResponse200) & {
  headers: Headers;
};
export type toolsControllerGetFxQuoteResponseError = (toolsControllerGetFxQuoteResponse400 | toolsControllerGetFxQuoteResponse401 | toolsControllerGetFxQuoteResponse403) & {
  headers: Headers;
};

export type toolsControllerGetFxQuoteResponse = (toolsControllerGetFxQuoteResponseSuccess | toolsControllerGetFxQuoteResponseError)

export const getToolsControllerGetFxQuoteUrl = () => {




  return `/tools/fx/quote`
}

export const toolsControllerGetFxQuote = async (fxQuoteDto: FxQuoteDto, options?: RequestInit): Promise<toolsControllerGetFxQuoteResponse> => {

  return customInstance<toolsControllerGetFxQuoteResponse>(getToolsControllerGetFxQuoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      fxQuoteDto,)
  }
);}




export const getToolsControllerGetFxQuoteMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxQuote>>, TError,{data: FxQuoteDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxQuote>>, TError,{data: FxQuoteDto}, TContext> => {

const mutationKey = ['toolsControllerGetFxQuote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toolsControllerGetFxQuote>>, {data: FxQuoteDto}> = (props) => {
          const {data} = props ?? {};

          return  toolsControllerGetFxQuote(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToolsControllerGetFxQuoteMutationResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetFxQuote>>>
    export type ToolsControllerGetFxQuoteMutationBody = FxQuoteDto
    export type ToolsControllerGetFxQuoteMutationError = ErrorType<BasicResponse>

    /**
 * @summary Get FX Quote
 */
export const useToolsControllerGetFxQuote = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxQuote>>, TError,{data: FxQuoteDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toolsControllerGetFxQuote>>,
        TError,
        {data: FxQuoteDto},
        TContext
      > => {
      return useMutation(getToolsControllerGetFxQuoteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get FX Buy Quote
 */
export type toolsControllerGetFxBuyQuoteResponse200 = {
  data: ResponseWrapperFxQuote
  status: 200
}

export type toolsControllerGetFxBuyQuoteResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetFxBuyQuoteResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetFxBuyQuoteResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetFxBuyQuoteResponseSuccess = (toolsControllerGetFxBuyQuoteResponse200) & {
  headers: Headers;
};
export type toolsControllerGetFxBuyQuoteResponseError = (toolsControllerGetFxBuyQuoteResponse400 | toolsControllerGetFxBuyQuoteResponse401 | toolsControllerGetFxBuyQuoteResponse403) & {
  headers: Headers;
};

export type toolsControllerGetFxBuyQuoteResponse = (toolsControllerGetFxBuyQuoteResponseSuccess | toolsControllerGetFxBuyQuoteResponseError)

export const getToolsControllerGetFxBuyQuoteUrl = () => {




  return `/tools/fx/quote/buy`
}

export const toolsControllerGetFxBuyQuote = async (fxBuyQuoteDto: FxBuyQuoteDto, options?: RequestInit): Promise<toolsControllerGetFxBuyQuoteResponse> => {

  return customInstance<toolsControllerGetFxBuyQuoteResponse>(getToolsControllerGetFxBuyQuoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      fxBuyQuoteDto,)
  }
);}




export const getToolsControllerGetFxBuyQuoteMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxBuyQuote>>, TError,{data: FxBuyQuoteDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxBuyQuote>>, TError,{data: FxBuyQuoteDto}, TContext> => {

const mutationKey = ['toolsControllerGetFxBuyQuote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toolsControllerGetFxBuyQuote>>, {data: FxBuyQuoteDto}> = (props) => {
          const {data} = props ?? {};

          return  toolsControllerGetFxBuyQuote(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToolsControllerGetFxBuyQuoteMutationResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetFxBuyQuote>>>
    export type ToolsControllerGetFxBuyQuoteMutationBody = FxBuyQuoteDto
    export type ToolsControllerGetFxBuyQuoteMutationError = ErrorType<BasicResponse>

    /**
 * @summary Get FX Buy Quote
 */
export const useToolsControllerGetFxBuyQuote = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxBuyQuote>>, TError,{data: FxBuyQuoteDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toolsControllerGetFxBuyQuote>>,
        TError,
        {data: FxBuyQuoteDto},
        TContext
      > => {
      return useMutation(getToolsControllerGetFxBuyQuoteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get FX Sell Quote
 */
export type toolsControllerGetFxSellQuoteResponse200 = {
  data: ResponseWrapperFxQuote
  status: 200
}

export type toolsControllerGetFxSellQuoteResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerGetFxSellQuoteResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerGetFxSellQuoteResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerGetFxSellQuoteResponseSuccess = (toolsControllerGetFxSellQuoteResponse200) & {
  headers: Headers;
};
export type toolsControllerGetFxSellQuoteResponseError = (toolsControllerGetFxSellQuoteResponse400 | toolsControllerGetFxSellQuoteResponse401 | toolsControllerGetFxSellQuoteResponse403) & {
  headers: Headers;
};

export type toolsControllerGetFxSellQuoteResponse = (toolsControllerGetFxSellQuoteResponseSuccess | toolsControllerGetFxSellQuoteResponseError)

export const getToolsControllerGetFxSellQuoteUrl = () => {




  return `/tools/fx/quote/sell`
}

export const toolsControllerGetFxSellQuote = async (fxSellQuoteDto: FxSellQuoteDto, options?: RequestInit): Promise<toolsControllerGetFxSellQuoteResponse> => {

  return customInstance<toolsControllerGetFxSellQuoteResponse>(getToolsControllerGetFxSellQuoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      fxSellQuoteDto,)
  }
);}




export const getToolsControllerGetFxSellQuoteMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxSellQuote>>, TError,{data: FxSellQuoteDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxSellQuote>>, TError,{data: FxSellQuoteDto}, TContext> => {

const mutationKey = ['toolsControllerGetFxSellQuote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toolsControllerGetFxSellQuote>>, {data: FxSellQuoteDto}> = (props) => {
          const {data} = props ?? {};

          return  toolsControllerGetFxSellQuote(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToolsControllerGetFxSellQuoteMutationResult = NonNullable<Awaited<ReturnType<typeof toolsControllerGetFxSellQuote>>>
    export type ToolsControllerGetFxSellQuoteMutationBody = FxSellQuoteDto
    export type ToolsControllerGetFxSellQuoteMutationError = ErrorType<BasicResponse>

    /**
 * @summary Get FX Sell Quote
 */
export const useToolsControllerGetFxSellQuote = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerGetFxSellQuote>>, TError,{data: FxSellQuoteDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toolsControllerGetFxSellQuote>>,
        TError,
        {data: FxSellQuoteDto},
        TContext
      > => {
      return useMutation(getToolsControllerGetFxSellQuoteMutationOptions(options), queryClient);
    }
    /**
 * @summary Upload Temp File
 */
export type toolsControllerUploadTempFileResponse200 = {
  data: ResponseWrapperTempFileUploadResult
  status: 200
}

export type toolsControllerUploadTempFileResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerUploadTempFileResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerUploadTempFileResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerUploadTempFileResponseSuccess = (toolsControllerUploadTempFileResponse200) & {
  headers: Headers;
};
export type toolsControllerUploadTempFileResponseError = (toolsControllerUploadTempFileResponse400 | toolsControllerUploadTempFileResponse401 | toolsControllerUploadTempFileResponse403) & {
  headers: Headers;
};

export type toolsControllerUploadTempFileResponse = (toolsControllerUploadTempFileResponseSuccess | toolsControllerUploadTempFileResponseError)

export const getToolsControllerUploadTempFileUrl = () => {




  return `/tools/temp-file/upload`
}

export const toolsControllerUploadTempFile = async ( options?: RequestInit): Promise<toolsControllerUploadTempFileResponse> => {

  return customInstance<toolsControllerUploadTempFileResponse>(getToolsControllerUploadTempFileUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getToolsControllerUploadTempFileMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerUploadTempFile>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof toolsControllerUploadTempFile>>, TError,void, TContext> => {

const mutationKey = ['toolsControllerUploadTempFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toolsControllerUploadTempFile>>, void> = () => {


          return  toolsControllerUploadTempFile(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToolsControllerUploadTempFileMutationResult = NonNullable<Awaited<ReturnType<typeof toolsControllerUploadTempFile>>>

    export type ToolsControllerUploadTempFileMutationError = ErrorType<BasicResponse>

    /**
 * @summary Upload Temp File
 */
export const useToolsControllerUploadTempFile = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerUploadTempFile>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toolsControllerUploadTempFile>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getToolsControllerUploadTempFileMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Temp File
 */
export type toolsControllerDeleteUploadTempFileResponse200 = {
  data: BasicResponse
  status: 200
}

export type toolsControllerDeleteUploadTempFileResponse400 = {
  data: BasicResponse
  status: 400
}

export type toolsControllerDeleteUploadTempFileResponse401 = {
  data: BasicResponse
  status: 401
}

export type toolsControllerDeleteUploadTempFileResponse403 = {
  data: BasicResponse
  status: 403
}

export type toolsControllerDeleteUploadTempFileResponseSuccess = (toolsControllerDeleteUploadTempFileResponse200) & {
  headers: Headers;
};
export type toolsControllerDeleteUploadTempFileResponseError = (toolsControllerDeleteUploadTempFileResponse400 | toolsControllerDeleteUploadTempFileResponse401 | toolsControllerDeleteUploadTempFileResponse403) & {
  headers: Headers;
};

export type toolsControllerDeleteUploadTempFileResponse = (toolsControllerDeleteUploadTempFileResponseSuccess | toolsControllerDeleteUploadTempFileResponseError)

export const getToolsControllerDeleteUploadTempFileUrl = (id: string,) => {




  return `/tools/temp-file/${id}`
}

export const toolsControllerDeleteUploadTempFile = async (id: string, options?: RequestInit): Promise<toolsControllerDeleteUploadTempFileResponse> => {

  return customInstance<toolsControllerDeleteUploadTempFileResponse>(getToolsControllerDeleteUploadTempFileUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getToolsControllerDeleteUploadTempFileMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerDeleteUploadTempFile>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof toolsControllerDeleteUploadTempFile>>, TError,{id: string}, TContext> => {

const mutationKey = ['toolsControllerDeleteUploadTempFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toolsControllerDeleteUploadTempFile>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  toolsControllerDeleteUploadTempFile(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToolsControllerDeleteUploadTempFileMutationResult = NonNullable<Awaited<ReturnType<typeof toolsControllerDeleteUploadTempFile>>>

    export type ToolsControllerDeleteUploadTempFileMutationError = ErrorType<BasicResponse>

    /**
 * @summary Delete Temp File
 */
export const useToolsControllerDeleteUploadTempFile = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toolsControllerDeleteUploadTempFile>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toolsControllerDeleteUploadTempFile>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getToolsControllerDeleteUploadTempFileMutationOptions(options), queryClient);
    }
