/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PaymentControllerGetAllParams
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Payments
 */
export type paymentControllerGetAllResponse200 = {
  data: void
  status: 200
}

export type paymentControllerGetAllResponseSuccess = (paymentControllerGetAllResponse200) & {
  headers: Headers;
};
;

export type paymentControllerGetAllResponse = (paymentControllerGetAllResponseSuccess)

export const getPaymentControllerGetAllUrl = (params?: PaymentControllerGetAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/payments?${stringifiedParams}` : `/payments`
}

export const paymentControllerGetAll = async (params?: PaymentControllerGetAllParams, options?: RequestInit): Promise<paymentControllerGetAllResponse> => {

  return customInstance<paymentControllerGetAllResponse>(getPaymentControllerGetAllUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPaymentControllerGetAllQueryKey = (params?: PaymentControllerGetAllParams,) => {
    return [
    `/payments`, ...(params ? [params] : [])
    ] as const;
    }


export const getPaymentControllerGetAllQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGetAll>>, TError = ErrorType<unknown>>(params?: PaymentControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGetAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGetAll>>> = ({ signal }) => paymentControllerGetAll(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGetAll>>>
export type PaymentControllerGetAllQueryError = ErrorType<unknown>


export function usePaymentControllerGetAll<TData = Awaited<ReturnType<typeof paymentControllerGetAll>>, TError = ErrorType<unknown>>(
 params: undefined |  PaymentControllerGetAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetAll<TData = Awaited<ReturnType<typeof paymentControllerGetAll>>, TError = ErrorType<unknown>>(
 params?: PaymentControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetAll<TData = Awaited<ReturnType<typeof paymentControllerGetAll>>, TError = ErrorType<unknown>>(
 params?: PaymentControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Payments
 */

export function usePaymentControllerGetAll<TData = Awaited<ReturnType<typeof paymentControllerGetAll>>, TError = ErrorType<unknown>>(
 params?: PaymentControllerGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGetAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get One Payment
 */
export type paymentControllerGetOneResponse200 = {
  data: void
  status: 200
}

export type paymentControllerGetOneResponseSuccess = (paymentControllerGetOneResponse200) & {
  headers: Headers;
};
;

export type paymentControllerGetOneResponse = (paymentControllerGetOneResponseSuccess)

export const getPaymentControllerGetOneUrl = (id: string,) => {




  return `/payments/${id}`
}

export const paymentControllerGetOne = async (id: string, options?: RequestInit): Promise<paymentControllerGetOneResponse> => {

  return customInstance<paymentControllerGetOneResponse>(getPaymentControllerGetOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPaymentControllerGetOneQueryKey = (id: string,) => {
    return [
    `/payments/${id}`
    ] as const;
    }


export const getPaymentControllerGetOneQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGetOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGetOne>>> = ({ signal }) => paymentControllerGetOne(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGetOne>>>
export type PaymentControllerGetOneQueryError = ErrorType<unknown>


export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get One Payment
 */

export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGetOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Payment Payout
 */
export type paymentControllerCreateResponse201 = {
  data: void
  status: 201
}

export type paymentControllerCreateResponseSuccess = (paymentControllerCreateResponse201) & {
  headers: Headers;
};
;

export type paymentControllerCreateResponse = (paymentControllerCreateResponseSuccess)

export const getPaymentControllerCreateUrl = () => {




  return `/payments/payout`
}

export const paymentControllerCreate = async ( options?: RequestInit): Promise<paymentControllerCreateResponse> => {

  return customInstance<paymentControllerCreateResponse>(getPaymentControllerCreateUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPaymentControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['paymentControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerCreate>>, void> = () => {


          return  paymentControllerCreate(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerCreate>>>

    export type PaymentControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary Create Payment Payout
 */
export const usePaymentControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerCreate>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPaymentControllerCreateMutationOptions(options), queryClient);
    }
    /**
 * @summary Generate Payment Receipt PDF
 */
export type paymentControllerGeneratePdfResponse200 = {
  data: void
  status: 200
}

export type paymentControllerGeneratePdfResponseSuccess = (paymentControllerGeneratePdfResponse200) & {
  headers: Headers;
};
;

export type paymentControllerGeneratePdfResponse = (paymentControllerGeneratePdfResponseSuccess)

export const getPaymentControllerGeneratePdfUrl = (id: string,) => {




  return `/payments/${id}/generate/pdf`
}

export const paymentControllerGeneratePdf = async (id: string, options?: RequestInit): Promise<paymentControllerGeneratePdfResponse> => {

  return customInstance<paymentControllerGeneratePdfResponse>(getPaymentControllerGeneratePdfUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPaymentControllerGeneratePdfQueryKey = (id: string,) => {
    return [
    `/payments/${id}/generate/pdf`
    ] as const;
    }


export const getPaymentControllerGeneratePdfQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGeneratePdfQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>> = ({ signal }) => paymentControllerGeneratePdf(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGeneratePdfQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>>
export type PaymentControllerGeneratePdfQueryError = ErrorType<unknown>


export function usePaymentControllerGeneratePdf<TData = Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGeneratePdf>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGeneratePdf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGeneratePdf<TData = Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGeneratePdf>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGeneratePdf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGeneratePdf<TData = Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Generate Payment Receipt PDF
 */

export function usePaymentControllerGeneratePdf<TData = Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGeneratePdfQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




