/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Allawee Infrastructure Backend APIs
 * The Allawee Infrastructure APIs description
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BasicResponse,
  CreatePayoutPaymentDto,
  PaymentControllerGeneratePDFParams,
  PaymentControllerGetCSVParams,
  PaymentControllerGetOneParams,
  PaymentControllerGetParams,
  ResponseWrapperApiHydratedPayment,
  ResponseWrapperApiHydratedPaymentList
} from '../model';

import { customInstance } from '../../lib/orvalClient';
import type { ErrorType } from '../../lib/orvalClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Payments
 */
export type paymentControllerGetResponse200 = {
  data: ResponseWrapperApiHydratedPaymentList
  status: 200
}

export type paymentControllerGetResponse400 = {
  data: BasicResponse
  status: 400
}

export type paymentControllerGetResponse401 = {
  data: BasicResponse
  status: 401
}

export type paymentControllerGetResponse403 = {
  data: BasicResponse
  status: 403
}

export type paymentControllerGetResponseSuccess = (paymentControllerGetResponse200) & {
  headers: Headers;
};
export type paymentControllerGetResponseError = (paymentControllerGetResponse400 | paymentControllerGetResponse401 | paymentControllerGetResponse403) & {
  headers: Headers;
};

export type paymentControllerGetResponse = (paymentControllerGetResponseSuccess | paymentControllerGetResponseError)

export const getPaymentControllerGetUrl = (params?: PaymentControllerGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/payments?${stringifiedParams}` : `/payments`
}

export const paymentControllerGet = async (params?: PaymentControllerGetParams, options?: RequestInit): Promise<paymentControllerGetResponse> => {

  return customInstance<paymentControllerGetResponse>(getPaymentControllerGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPaymentControllerGetQueryKey = (params?: PaymentControllerGetParams,) => {
    return [
    `/payments`, ...(params ? [params] : [])
    ] as const;
    }


export const getPaymentControllerGetQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGet>>, TError = ErrorType<BasicResponse>>(params?: PaymentControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGet>>> = ({ signal }) => paymentControllerGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGetQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGet>>>
export type PaymentControllerGetQueryError = ErrorType<BasicResponse>


export function usePaymentControllerGet<TData = Awaited<ReturnType<typeof paymentControllerGet>>, TError = ErrorType<BasicResponse>>(
 params: undefined |  PaymentControllerGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGet>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGet<TData = Awaited<ReturnType<typeof paymentControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: PaymentControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGet>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGet<TData = Awaited<ReturnType<typeof paymentControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: PaymentControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Payments
 */

export function usePaymentControllerGet<TData = Awaited<ReturnType<typeof paymentControllerGet>>, TError = ErrorType<BasicResponse>>(
 params?: PaymentControllerGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get One Payment
 */
export type paymentControllerGetOneResponse200 = {
  data: ResponseWrapperApiHydratedPayment
  status: 200
}

export type paymentControllerGetOneResponse400 = {
  data: BasicResponse
  status: 400
}

export type paymentControllerGetOneResponse401 = {
  data: BasicResponse
  status: 401
}

export type paymentControllerGetOneResponse403 = {
  data: BasicResponse
  status: 403
}

export type paymentControllerGetOneResponse404 = {
  data: BasicResponse
  status: 404
}

export type paymentControllerGetOneResponseSuccess = (paymentControllerGetOneResponse200) & {
  headers: Headers;
};
export type paymentControllerGetOneResponseError = (paymentControllerGetOneResponse400 | paymentControllerGetOneResponse401 | paymentControllerGetOneResponse403 | paymentControllerGetOneResponse404) & {
  headers: Headers;
};

export type paymentControllerGetOneResponse = (paymentControllerGetOneResponseSuccess | paymentControllerGetOneResponseError)

export const getPaymentControllerGetOneUrl = (id: string,
    params?: PaymentControllerGetOneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/payments/${id}?${stringifiedParams}` : `/payments/${id}`
}

export const paymentControllerGetOne = async (id: string,
    params?: PaymentControllerGetOneParams, options?: RequestInit): Promise<paymentControllerGetOneResponse> => {

  return customInstance<paymentControllerGetOneResponse>(getPaymentControllerGetOneUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPaymentControllerGetOneQueryKey = (id: string,
    params?: PaymentControllerGetOneParams,) => {
    return [
    `/payments/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getPaymentControllerGetOneQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: PaymentControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGetOneQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGetOne>>> = ({ signal }) => paymentControllerGetOne(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGetOne>>>
export type PaymentControllerGetOneQueryError = ErrorType<BasicResponse>


export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  PaymentControllerGetOneParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: PaymentControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGetOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: PaymentControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get One Payment
 */

export function usePaymentControllerGetOne<TData = Awaited<ReturnType<typeof paymentControllerGetOne>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: PaymentControllerGetOneParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGetOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGetOneQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Payment Payout
 */
export type paymentControllerPayoutResponse201 = {
  data: ResponseWrapperApiHydratedPayment
  status: 201
}

export type paymentControllerPayoutResponse400 = {
  data: BasicResponse
  status: 400
}

export type paymentControllerPayoutResponse401 = {
  data: BasicResponse
  status: 401
}

export type paymentControllerPayoutResponse403 = {
  data: BasicResponse
  status: 403
}

export type paymentControllerPayoutResponseSuccess = (paymentControllerPayoutResponse201) & {
  headers: Headers;
};
export type paymentControllerPayoutResponseError = (paymentControllerPayoutResponse400 | paymentControllerPayoutResponse401 | paymentControllerPayoutResponse403) & {
  headers: Headers;
};

export type paymentControllerPayoutResponse = (paymentControllerPayoutResponseSuccess | paymentControllerPayoutResponseError)

export const getPaymentControllerPayoutUrl = () => {




  return `/payments/payout`
}

export const paymentControllerPayout = async (createPayoutPaymentDto: CreatePayoutPaymentDto, options?: RequestInit): Promise<paymentControllerPayoutResponse> => {

  return customInstance<paymentControllerPayoutResponse>(getPaymentControllerPayoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPayoutPaymentDto,)
  }
);}




export const getPaymentControllerPayoutMutationOptions = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerPayout>>, TError,{data: CreatePayoutPaymentDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerPayout>>, TError,{data: CreatePayoutPaymentDto}, TContext> => {

const mutationKey = ['paymentControllerPayout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerPayout>>, {data: CreatePayoutPaymentDto}> = (props) => {
          const {data} = props ?? {};

          return  paymentControllerPayout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PaymentControllerPayoutMutationResult = NonNullable<Awaited<ReturnType<typeof paymentControllerPayout>>>
    export type PaymentControllerPayoutMutationBody = CreatePayoutPaymentDto
    export type PaymentControllerPayoutMutationError = ErrorType<BasicResponse>

    /**
 * @summary Create Payment Payout
 */
export const usePaymentControllerPayout = <TError = ErrorType<BasicResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof paymentControllerPayout>>, TError,{data: CreatePayoutPaymentDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof paymentControllerPayout>>,
        TError,
        {data: CreatePayoutPaymentDto},
        TContext
      > => {
      return useMutation(getPaymentControllerPayoutMutationOptions(options), queryClient);
    }
    /**
 * @summary Generate Payment Receipt PDF
 */
export type paymentControllerGeneratePDFResponse200 = {
  data: BasicResponse
  status: 200
}

export type paymentControllerGeneratePDFResponse400 = {
  data: BasicResponse
  status: 400
}

export type paymentControllerGeneratePDFResponse401 = {
  data: BasicResponse
  status: 401
}

export type paymentControllerGeneratePDFResponse403 = {
  data: BasicResponse
  status: 403
}

export type paymentControllerGeneratePDFResponse404 = {
  data: BasicResponse
  status: 404
}

export type paymentControllerGeneratePDFResponseSuccess = (paymentControllerGeneratePDFResponse200) & {
  headers: Headers;
};
export type paymentControllerGeneratePDFResponseError = (paymentControllerGeneratePDFResponse400 | paymentControllerGeneratePDFResponse401 | paymentControllerGeneratePDFResponse403 | paymentControllerGeneratePDFResponse404) & {
  headers: Headers;
};

export type paymentControllerGeneratePDFResponse = (paymentControllerGeneratePDFResponseSuccess | paymentControllerGeneratePDFResponseError)

export const getPaymentControllerGeneratePDFUrl = (id: string,
    params?: PaymentControllerGeneratePDFParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/payments/${id}/generate/pdf?${stringifiedParams}` : `/payments/${id}/generate/pdf`
}

export const paymentControllerGeneratePDF = async (id: string,
    params?: PaymentControllerGeneratePDFParams, options?: RequestInit): Promise<paymentControllerGeneratePDFResponse> => {

  return customInstance<paymentControllerGeneratePDFResponse>(getPaymentControllerGeneratePDFUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPaymentControllerGeneratePDFQueryKey = (id: string,
    params?: PaymentControllerGeneratePDFParams,) => {
    return [
    `/payments/${id}/generate/pdf`, ...(params ? [params] : [])
    ] as const;
    }


export const getPaymentControllerGeneratePDFQueryOptions = <TData = Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError = ErrorType<BasicResponse>>(id: string,
    params?: PaymentControllerGeneratePDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPaymentControllerGeneratePDFQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>> = ({ signal }) => paymentControllerGeneratePDF(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PaymentControllerGeneratePDFQueryResult = NonNullable<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>>
export type PaymentControllerGeneratePDFQueryError = ErrorType<BasicResponse>


export function usePaymentControllerGeneratePDF<TData = Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params: undefined |  PaymentControllerGeneratePDFParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGeneratePDF>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGeneratePDF>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGeneratePDF<TData = Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: PaymentControllerGeneratePDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentControllerGeneratePDF>>,
          TError,
          Awaited<ReturnType<typeof paymentControllerGeneratePDF>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePaymentControllerGeneratePDF<TData = Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: PaymentControllerGeneratePDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Generate Payment Receipt PDF
 */

export function usePaymentControllerGeneratePDF<TData = Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError = ErrorType<BasicResponse>>(
 id: string,
    params?: PaymentControllerGeneratePDFParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof paymentControllerGeneratePDF>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPaymentControllerGeneratePDFQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Download All Payments in CSV
 */
export type paymentControllerGetCSVResponse200 = {
  data: Blob
  status: 200
}

export type paymentControllerGetCSVResponse400 = {
  data: BasicResponse
  status: 400
}

export type paymentControllerGetCSVResponse401 = {
  data: BasicResponse
  status: 401
}

export type paymentControllerGetCSVResponse403 = {
  data: BasicResponse
  status: 403
}

export type paymentControllerGetCSVResponseSuccess = (paymentControllerGetCSVResponse200) & {
  headers: Headers;
};
export type paymentControllerGetCSVResponseError = (paymentControllerGetCSVResponse400 | paymentControllerGetCSVResponse401 | paymentControllerGetCSVResponse403) & {
  headers: Headers;
};

export type paymentControllerGetCSVResponse = (paymentControllerGetCSVResponseSuccess | paymentControllerGetCSVResponseError)

export const getPaymentControllerGetCSVUrl = (params?: PaymentControllerGetCSVParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/payments/csv?${stringifiedParams}` : `/payments/csv`
}

export const paymentControllerGetCSV = async (params?: PaymentControllerGetCSVParams, options?: RequestInit): Promise<paymentControllerGetCSVResponse> => {

  return customInstance<paymentControllerGetCSVResponse>(getPaymentControllerGetCSVUrl(params),
  {
    ...options,
    method: 'GET'
  }
);}


