// API base URLs — swap via VITE_* env vars at build time
export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ?? 'https://gateway.withpropeller.com'

export const DOCS_URL =
  import.meta.env.VITE_DOCS_URL ?? 'https://docs.withpropeller.com'

// localStorage keys
export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'alw_access_token',
  USER_DATA: 'alw_user_data',
  BUSINESS_DATA: 'alw_business_data',
  SIDEBAR_STATE: 'alw_sidebar_state',
  MFA_SKIP: 'alw_mfa_skip',
  DASHBOARD_MODE: 'alw_dashboard_mode',
}

// Response status codes from the Infra API
export const API_STATUS = {
  SUCCESS: 'success',
  MFA_REQUIRED: 'mfa-required',
  PENDING: 'account-pending',
}

// Country list — Africa prioritised, then Americas, Europe, Asia & Middle East, Oceania
export interface Country {
  code: string
  name: string
  dialCode: string
}

export const COUNTRIES: Country[] = [
  // Africa
  { code: 'NG', name: 'Nigeria', dialCode: '+234' },
  { code: 'GH', name: 'Ghana', dialCode: '+233' },
  { code: 'KE', name: 'Kenya', dialCode: '+254' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27' },
  { code: 'EG', name: 'Egypt', dialCode: '+20' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255' },
  { code: 'UG', name: 'Uganda', dialCode: '+256' },
  { code: 'SN', name: 'Senegal', dialCode: '+221' },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250' },
  { code: 'MA', name: 'Morocco', dialCode: '+212' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216' },
  { code: 'LY', name: 'Libya', dialCode: '+218' },
  { code: 'SD', name: 'Sudan', dialCode: '+249' },
  { code: 'SS', name: 'South Sudan', dialCode: '+211' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263' },
  { code: 'AO', name: 'Angola', dialCode: '+244' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230' },
  { code: 'BJ', name: 'Benin', dialCode: '+229' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226' },
  { code: 'ML', name: 'Mali', dialCode: '+223' },
  { code: 'NE', name: 'Niger', dialCode: '+227' },
  { code: 'TD', name: 'Chad', dialCode: '+235' },
  { code: 'TG', name: 'Togo', dialCode: '+228' },
  { code: 'GA', name: 'Gabon', dialCode: '+241' },
  { code: 'GN', name: 'Guinea', dialCode: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232' },
  { code: 'LR', name: 'Liberia', dialCode: '+231' },
  { code: 'GM', name: 'Gambia', dialCode: '+220' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222' },
  { code: 'SO', name: 'Somalia', dialCode: '+252' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236' },
  { code: 'CG', name: 'Congo', dialCode: '+242' },
  { code: 'CD', name: 'DR Congo', dialCode: '+243' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240' },
  { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239' },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248' },
  { code: 'KM', name: 'Comoros', dialCode: '+269' },
  { code: 'BI', name: 'Burundi', dialCode: '+257' },
  { code: 'MW', name: 'Malawi', dialCode: '+265' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268' },
  { code: 'BW', name: 'Botswana', dialCode: '+267' },
  { code: 'NA', name: 'Namibia', dialCode: '+264' },
  // Americas
  { code: 'US', name: 'United States', dialCode: '+1' },
  { code: 'CA', name: 'Canada', dialCode: '+1' },
  { code: 'BR', name: 'Brazil', dialCode: '+55' },
  { code: 'MX', name: 'Mexico', dialCode: '+52' },
  { code: 'AR', name: 'Argentina', dialCode: '+54' },
  { code: 'CO', name: 'Colombia', dialCode: '+57' },
  { code: 'CL', name: 'Chile', dialCode: '+56' },
  { code: 'PE', name: 'Peru', dialCode: '+51' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598' },
  { code: 'GY', name: 'Guyana', dialCode: '+592' },
  { code: 'SR', name: 'Suriname', dialCode: '+597' },
  { code: 'PA', name: 'Panama', dialCode: '+507' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505' },
  { code: 'HN', name: 'Honduras', dialCode: '+504' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503' },
  { code: 'BZ', name: 'Belize', dialCode: '+501' },
  { code: 'CU', name: 'Cuba', dialCode: '+53' },
  { code: 'HT', name: 'Haiti', dialCode: '+509' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1849' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1876' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868' },
  { code: 'BB', name: 'Barbados', dialCode: '+1246' },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1758' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1784' },
  { code: 'GD', name: 'Grenada', dialCode: '+1473' },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268' },
  { code: 'DM', name: 'Dominica', dialCode: '+1767' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1242' },
  // Europe
  { code: 'GB', name: 'United Kingdom', dialCode: '+44' },
  { code: 'DE', name: 'Germany', dialCode: '+49' },
  { code: 'FR', name: 'France', dialCode: '+33' },
  { code: 'IT', name: 'Italy', dialCode: '+39' },
  { code: 'ES', name: 'Spain', dialCode: '+34' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31' },
  { code: 'PT', name: 'Portugal', dialCode: '+351' },
  { code: 'PL', name: 'Poland', dialCode: '+48' },
  { code: 'RU', name: 'Russia', dialCode: '+7' },
  { code: 'TR', name: 'Turkey', dialCode: '+90' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380' },
  { code: 'SE', name: 'Sweden', dialCode: '+46' },
  { code: 'NO', name: 'Norway', dialCode: '+47' },
  { code: 'DK', name: 'Denmark', dialCode: '+45' },
  { code: 'FI', name: 'Finland', dialCode: '+358' },
  { code: 'BE', name: 'Belgium', dialCode: '+32' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41' },
  { code: 'AT', name: 'Austria', dialCode: '+43' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420' },
  { code: 'HU', name: 'Hungary', dialCode: '+36' },
  { code: 'RO', name: 'Romania', dialCode: '+40' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359' },
  { code: 'HR', name: 'Croatia', dialCode: '+385' },
  { code: 'RS', name: 'Serbia', dialCode: '+381' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386' },
  { code: 'GR', name: 'Greece', dialCode: '+30' },
  { code: 'IE', name: 'Ireland', dialCode: '+353' },
  { code: 'IS', name: 'Iceland', dialCode: '+354' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352' },
  { code: 'MT', name: 'Malta', dialCode: '+356' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370' },
  { code: 'LV', name: 'Latvia', dialCode: '+371' },
  { code: 'EE', name: 'Estonia', dialCode: '+372' },
  { code: 'BY', name: 'Belarus', dialCode: '+375' },
  { code: 'MD', name: 'Moldova', dialCode: '+373' },
  { code: 'AL', name: 'Albania', dialCode: '+355' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382' },
  { code: 'GE', name: 'Georgia', dialCode: '+995' },
  { code: 'AM', name: 'Armenia', dialCode: '+374' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994' },
  // Asia & Middle East
  { code: 'IN', name: 'India', dialCode: '+91' },
  { code: 'CN', name: 'China', dialCode: '+86' },
  { code: 'JP', name: 'Japan', dialCode: '+81' },
  { code: 'KR', name: 'South Korea', dialCode: '+82' },
  { code: 'SG', name: 'Singapore', dialCode: '+65' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60' },
  { code: 'TH', name: 'Thailand', dialCode: '+66' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84' },
  { code: 'PH', name: 'Philippines', dialCode: '+63' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94' },
  { code: 'NP', name: 'Nepal', dialCode: '+977' },
  { code: 'AF', name: 'Afghanistan', dialCode: '+93' },
  { code: 'IR', name: 'Iran', dialCode: '+98' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964' },
  { code: 'SY', name: 'Syria', dialCode: '+963' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961' },
  { code: 'JO', name: 'Jordan', dialCode: '+962' },
  { code: 'IL', name: 'Israel', dialCode: '+972' },
  { code: 'PS', name: 'Palestine', dialCode: '+970' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973' },
  { code: 'QA', name: 'Qatar', dialCode: '+974' },
  { code: 'OM', name: 'Oman', dialCode: '+968' },
  { code: 'YE', name: 'Yemen', dialCode: '+967' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852' },
  { code: 'MV', name: 'Maldives', dialCode: '+960' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975' },
  // Oceania
  { code: 'AU', name: 'Australia', dialCode: '+61' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678' },
  { code: 'WS', name: 'Samoa', dialCode: '+685' },
  { code: 'TO', name: 'Tonga', dialCode: '+676' },
]

/** Unique countries for signup and other country pickers. */
export const SIGNUP_COUNTRIES: Country[] = COUNTRIES.filter(
  (c, i, arr) => arr.findIndex((x) => x.code === c.code) === i,
)
