# Default values for allawee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
version: v1

# Service Specific Values
image:
    repository: {{{ deployment.REPOSITORY }}}

## Application level settings
app:
    env:
        #[security]
        NODE_ENV: {{ deployment.ENV }}
        LOG_LEVEL: debug

        #[swagger]
        ENABLE_SWAGGER: true

        #[domains]
        APP_HOST: infrasrv-{{ deployment.ENV }}.allawee.com
        INFRA_WEB_DOMAIN: https://infra-{{ deployment.ENV }}.allawee.com
        MAIN_SITE_DOMAIN: https://{{ deployment.ENV }}.allawee.com

        #[external-integrations]
        SLACK_EVENTS_CHANNEL: infra-events-{{ deployment.ENV }}

        AWS_REGION: eu-west-1
        S3_DOCUMENT_STORE_BUCKET: cc-document-store-{{ deployment.ENV }}
